# -----------------------  Installation hint  -----------------------
#                          !!! Important !!!
#  This is the default values file - if you're editing this as
#  part of the ODS pipeline installation you're in the wrong file!
#
#  Please open ../values.yaml (the file you have created by making
#  a copy of ../values.yaml.tmpl) and do your changes there.
# -----------------------  Installation hint  -----------------------

# General
# Serviceaccount name to use for pipeline resources.
serviceAccountName: 'pipeline'
# Whether to enable debug mode
debug: 'false'

# Bitbucket
# Bitbucket URL (including scheme, without trailing slash).
# Example: https://bitbucket.example.com.
bitbucketUrl: ''
# Bitbucket username. Example: cd_user.
bitbucketUsername: ''

# Nexus
# Nexus URL (including scheme, without trailing slash).
# Example: https://nexus.example.com.
nexusUrl: ''
# Nexus username. Example: developer.
nexusUsername: ''

# Cluster
# URL (including scheme, without trailing slash) of the OpenShift Web Console.
consoleUrl: ''

# Notification Webhook
notification:
  # Whether notifications should be sent to the URL specified below or not.
  enabled: false
  # URL of the configured webhook
  url: 'http://example.com'
  # The HTTP method to be used
  method: 'POST'
  # The HTTP content type header
  contentType: 'application/json'
  # Specify the outcomes you want to be notified of (allowed values: c.f.
  # https://tekton.dev/docs/pipelines/pipelines/#using-aggregate-execution-status-of-all-tasks)
  notifyOnStatus:
    - 'Failed'
  # Template to be processed and accepted by the configured webhook in use
  # Below example might work for Microsoft Teams
  requestTemplate: |-
    {
      "@type": "MessageCard",
      "@context": "http://schema.org/extensions",
      "themeColor": {{if eq .OverallStatus "Succeeded"}}"237b4b"{{else}}"c4314b"{{ end }},
      "summary": "{{.ODSContext.Project}} - ODS Pipeline Run {{.PipelineRunName}} finished with status {{.OverallStatus}}",
      "sections": [
        {
          "activityTitle": "ODS Pipeline Run {{.PipelineRunName}} finished with status {{.OverallStatus}}",
          "activitySubtitle": "On Project {{.ODSContext.Project}}",
          "activityImage": "https://avatars.githubusercontent.com/u/38974438?s=200&v=4",
          "facts": [
            {
              "name": "GitRef",
              "value": "{{.ODSContext.GitRef}}"
            }
          ],
          "markdown": true
        }
      ],
      "potentialAction": [
        {
          "@type": "OpenUri",
          "name": "Go to PipelineRun",
          "targets": [
            {
              "os": "default",
              "uri": "{{.PipelineRunURL}}"
            }
          ]
        }
      ]
    }

# Pipeline(Run) Pruning
# Minimum hours to keep a pipeline run. Has precendence over pipelineRunMaxKeepRuns.
# Must be at least 1.
pipelineRunMinKeepHours: '48'
# Maximum number of pipeline runs to keep.
# Must be at least 1.
pipelineRunMaxKeepRuns: '20'

# Pipeline Manager
pipelineManager:
  # PVC (used for the pipeline workspace)
  # Storage provisioner.
  storageProvisioner: ''
  # Storage class.
  storageClassName: ''
  # Storage size. Defaults to 2Gi unless set explicitly here.
  storageSize: '5Gi'
  # Number of replicas to run for the pipeline manager.
  replicaCount: 1
  # Deployment pod resources. Typically these settings should not need to change.
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Image repository to pull start/finish task images from.
imageRepository: ghcr.io/opendevstack/ods-pipeline
