kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-python-toolset
spec:
  output:
    to:
      name: "ods-python-toolset:0.1.0"
  source:
    git:
      uri: https://github.com/opendevstack/ods-pipeline
      ref: master # v0.1.0
