- op: replace
  path: /metadata/name
  value: ods-build-python-v0-1-0
- op: replace
  path: /spec/steps/0/image
  value: image-registry.openshift-image-registry.svc:5000/ods/ods-python-toolset:0.1.0
- op: replace
  path: /spec/steps/1/image
  value: image-registry.openshift-image-registry.svc:5000/ods/ods-sonar:0.1.0
