kind: ConfigMap
apiVersion: v1
metadata:
  name: ods-cluster
  labels:
    {{- include "chart.labels" . | nindent 4}}
data:
  consoleUrl: '{{required "consoleUrl is required" .Values.consoleUrl | trimSuffix "/"}}'
