kind: ConfigMap
apiVersion: v1
metadata:
  name: ods-nexus
  labels:
    {{- include "chart.labels" . | nindent 4}}
data:
  url: '{{required "nexusUrl is required" .Values.nexusUrl | trimSuffix "/"}}'
