kind: ConfigMap
apiVersion: v1
metadata:
  name: ods-bitbucket
  labels:
    {{- include "chart.labels" . | nindent 4}}
data:
  url: '{{required "bitbucketUrl is required" .Values.bitbucketUrl | trimSuffix "/"}}'
  repoBase: '{{required "bitbucketUrl is required" .Values.bitbucketUrl | trimSuffix "/"}}/scm'
