apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" .}}
  labels:
    {{- include "chart.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4}}
