
# Source: tasks/templates/task-ods-start.yaml
apiVersion: tekton.dev/v1beta1
kind: 'Task'
metadata:
  name: 'ods-start'
  annotations:
    "helm.sh/resource-policy": keep
spec:
  description: |
    Starts the pipeline run.

    See https://github.com/opendevstack/ods-pipeline/blob/v0.11.1/docs/tasks/ods-start.adoc
  params:
    - name: url
      description: Git URL to clone
      type: string
    - name: git-full-ref
      description: 'Git revision to checkout (branch, tag, sha, ref, ...)'
      type: string
      default: ''
    - name: submodules
      description: Defines if the resource should initialize and fetch the submodules.
      type: string
      default: 'true'
    - name: depth
      description: >-
        Performs a shallow clone where only the most recent commit(s) will be
        fetched.
      type: string
      default: '1'
    - name: http-proxy
      description: Git HTTP proxy server for non-SSL requests.
      type: string
      default: ''
    - name: https-proxy
      description: Git HTTPS proxy server for SSL requests.
      type: string
      default: ''
    - name: no-proxy
      description: Git no proxy - opt out of proxying HTTP/HTTPS requests.
      type: string
      default: ''
    - name: project
      description: >-
        Name of the project to build.
        The project is equal to the Bitbucket project of the repository to clone.
      type: string
    - name: environment
      description: >-
        Name of the environment to deploy to.
      type: string
    - name: version
      description: >-
        Version of the application.
        If not set, version will default to `WIP`.
      type: string
    - name: pr-key
      description: >-
        Bitbucket pull request key.
        Empty if there is no open PR for the specified Git branch.
      type: string
      default: ''
    - name: pr-base
      description: >-
        Bitbucket pull request base branch.
        Empty if there is no open PR for the specified Git branch.
      type: string
      default: ''
    - name: pipeline-run-name
      description: Name of pipeline run.
      type: string
    - name: cache-build-tasks-for-days
      description: >-
        Number of days build tasks are cached to enable build skipping.
        A subsequent build reusing the cache resets the time for that cache location.
      type: string
      default: '7'
  results:
    - description: The commit SHA that was fetched by this task.
      name: commit
    - description: The URL that was fetched by this task.
      name: url
  steps:
    - name: ods-start
      # Image is built from build/package/Dockerfile.start.
      image: 'ghcr.io/opendevstack/ods-pipeline/ods-start:0.11.1'
      env:
        - name: HOME
          value: '/tekton/home'
        - name: NEXUS_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-nexus
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: ods-nexus-auth
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-nexus-auth
        - name: NEXUS_TEMPORARY_REPOSITORY
          valueFrom:
            configMapKeyRef:
              key: temporaryRepository
              name: ods-nexus
        - name: NEXUS_PERMANENT_REPOSITORY
          valueFrom:
            configMapKeyRef:
              key: permanentRepository
              name: ods-nexus
        - name: BITBUCKET_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-bitbucket
        - name: BITBUCKET_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-bitbucket-auth
        - name: CONSOLE_URL
          valueFrom:
            configMapKeyRef:
              key: consoleUrl
              name: ods-cluster
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: ods-pipeline
      resources: {}
      script: |
        if [ -f /etc/ssl/certs/private-cert.pem ]; then
          cat /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/private-cert.pem > /tekton/home/git-cert.pem
          git config --global http.sslCAInfo /tekton/home/git-cert.pem
        fi

        # ods-start is built from cmd/start/main.go.
        ods-start \
          -project=$(params.project) \
          -environment=$(params.environment) \
          -version=$(params.version) \
          -git-full-ref=$(params.git-full-ref) \
          -url=$(params.url) \
          -pr-key=$(params.pr-key) \
          -pr-base=$(params.pr-base) \
          -http-proxy=$(params.http-proxy) \
          -https-proxy=$(params.https-proxy) \
          -no-proxy=$(params.no-proxy) \
          -submodules=$(params.submodules) \
          -depth=$(params.depth) \
          -pipeline-run-name=$(params.pipeline-run-name)

        cp .ods/git-commit-sha $(results.commit.path)

        echo -n "$(params.url)" > $(results.url.path)
      volumeMounts:
        - mountPath: /etc/ssl/certs/private-cert.pem
          name: private-cert
          readOnly: true
          subPath: tls.crt
      workingDir: $(workspaces.source.path)
  volumes:
    - name: private-cert
      secret:
        secretName: ods-private-cert
        optional: true
  workspaces:
    - description: The git repo will be cloned onto the volume backing this workspace
      name: source
