ARG imageTag="latest"

FROM ghcr.io/opendevstack/ods-pipeline/ods-node18-npm-toolset:$imageTag

ARG privateCertServer
USER root
RUN if [ -n "${privateCertServer}" ]; then openssl s_client -showcerts -connect "${privateCertServer}" </dev/null \
    | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > "/etc/pki/ca-trust/source/anchors/${privateCertServer%:*}.pem" && \
    update-ca-trust; fi
USER 1001
