ARG from=""
FROM $from

RUN echo "sonar.forceAuthentication=true" >> conf/sonar.properties

# Uncomment the following line to see debug output, e.g. in case SonarQube is
# not starting up properly.
# RUN echo "sonar.log.level=DEBUG" >> conf/sonar.properties
