= Software Architecture
:sectnums:
:toc:

== Purpose and Scope

The purpose of this document is to describe the architecture of the software system. It shall provide a graphical overview of the software system, its structure and interfaces to internal and external components.

== Definitions and Abbreviations

=== Abbreviations

[cols="1,5"]
|===
| Abbreviation | Description

| ODS
| OpenDevStack
|===

== References

N/A

== {doctitle}

=== Software System Overview

ODS Pipeline is used alongside an existing ODS Core installation. It is a replacement for Jenkins as the CI/CD engine. The following diagram illustrates the relationship of ODS Pipeline to external systems:

image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/docs/architecture/system-context.puml[System Context]

The following diagram illustrates in more detail how the various components interact:

image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/docs/architecture/container-system.puml[Software System]

As the diagram above shows, the ODS Pipeline installation is made up of one container installed by project admins (once per project) containing configuration (config maps and secrets), the pipeline manager and task resources (Tekton task definitions and their referenced images). The following diagram shows more detail about the installation:

image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/docs/architecture/component-namespaced-installation.puml[Namespaced Installation]

=== Interfaces

|===
|Source |Action |Protocol |Destination |Comment

| Bitbucket
| Webhook Trigger
| HTTP POST request
| ODS Pipeline Installation
| Endpoint is an exposed event listener.

| Task `ods-start`
| Checkout repository
| Git
| Bitbucket
|

| Task `ods-start`
| Set build status
| HTTP / JSON API
| Bitbucket
|

| Task `ods-start`
| Download existing artifacts
| HTTP / JSON API
| Nexus
|

| Task `ods-build-go`, task `ods-build-python`, task `ods-build-typescript`, task `ods-build-gradle`
| Analyze source code
| HTTP / JSON API
| SonarQube
|

| Task `ods-build-python`, task `ods-build-typescript`, task `ods-build-gradle`
| Download dependencies
| HTTP
| Nexus
| Nexus serves as a proxy for third party dependencies (e.g. hosted on NPM), and serves private dependencies hosted in Nexus as well.

| Task `ods-package-image`
| Scan for vulnerabilities
| HTTP / JSON API
| Aqua
|

| Task `ods-package-image`
| Push image
| HTTP
| OpenShift ImageStream
|

| Task `ods-deploy-helm`
| Copy image
| HTTP
| OpenShift ImageStream
|

| Task `ods-deploy-helm`
| Install/Upgrade release
| HTTP / JSON API
| OpenShift project
|

| Task `ods-finish`
| Set build status
| HTTP / JSON API
| Bitbucket
|

| Task `ods-finish`
| Upload artifacts
| HTTP / JSON API
| Nexus
|

| Task `ods-finish`
| Send notifications
| HTTP / API
| Configured notification service
|

| Binary `artifact-download`
| Retrieve configuration and secrets
| HTTP / JSON API
| OpenShift
|

| Binary `artifact-download`
| Retrieve Git revisions
| HTTP / JSON API
| Bitbucket
|

| Binary `artifact-download`
| Download artifacts
| HTTP / JSON API
| Nexus
|


|===

=== Hosting Environment

ODS Pipeline runs on Redhat OpenShift Container Platform, and is embedded into an installation of OpenDevStack.

== Deployment

There is one major deployment (typically in the project's cd-namespace) of the system managed by project administrators.

The installation provides the tasks that projects can consume as `Task` resources. It allows triggering pipelines in response to Bitbucket events.

The deployment is described in a Helm chart. For details, see the link:../installation.adoc[Installation Guide].

== Appendix

N/A

== Document History

As this document is version controlled in Git, all changes are tracked as commits. The history of changes to this file can be retrieved via `git log --oneline --no-merges docs/design/software-architecture.adoc`.
