= Software Design Specification
:sectnums:
:toc:

== Purpose

The purpose of this document is to describe the technical realization of the given software system architecture and the software requirements. It states how the design meets the requirements.

== Scope

The following software design specification will provide the technical realization of ODS pipeline version 0.1.

== Definitions and Abbreviations

N/A

== References

N/A

== {doctitle}

=== Developed components

As described in the architecture, the system is split into two main containers: a central installation and multiple local user installations. This document follows that structure.

==== Central ODS Pipeline Installation

===== Shared `ods-sonar` image

[cols="1,1,3"]
|===
| SDS-SHARED-1
| `ods-sonar` container image
| Container image for SQ scanning. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes software to analyze source code statically (SDS-SHARED-2, SDS-EXT-7, SDS-EXT-8 and SDS-EXT-9).

| SDS-SHARED-2
| `sonar` binary
a| Logic of SQ scanning. It runs `sonar-scanner` (SDS-EXT-7) on the sources, communicating with the SonarQube server specified by the `ods-sonar` config map and the `ods-sonar-auth` secret. After scanning, reports a generated using `cnes-report` (SDS-EXT-8) unless the scan is against a pull request. `cnes-report` is not compatible with PR scans, and reports are not needed for pull requests anyway as the evidence they provide is only needed for long-lived branches.

The project name is fixed to `<PROJECT>-<COMPONENT>`.

If the server edition supports it, the branch parameter shall be set, unless the branch being built belongs to an open PR, in which case PR analysis parameter shall be sent instead.
|===

===== Shared scripts

[cols="1,1,3"]
|===
| SDS-SHARED-3
| `supply-sonar-project-properties-default.sh` shell script
| Checks for `sonar-project.properties` file in the working directory. If that does not exist, the default properties file supplied in the container image is copied into the working directory.
|===


===== `ods-build-go` task

[cols="1,1,3"]
|===
| SDS-TASK-1
| `ods-build-go` ClusterTask resource
a| The task defines two steps:

. Build Go (module) applications (referencing SDS-TASK-2 and executing SDS-TASK-3)
. Analyze source code (referencing SDS-SHARED-1 and executing SDS-SHARED-2)

Input parameters:

* `working-dir`: allows to customize which directory is used as the Go module root. If set, artifacts are prefixed with `<SUBDIRECTORY>-`, and the SQ project is suffixed with `-<SUBDIRECTORY>`.
* `enable-cgo`: allows to enable `CGO`
* `go-os`: sets target operating system (`GOOS`)
* `go-arch`: sets target architecture (`GOARCH`)
* `output-dir`: sets destination directory of built binary
* `pre-test-script`: specifies script to run prior to tests
* `sonar-quality-gate`: enables quality gate check
* `sonar-skip`: skips SonarQube analysis

| SDS-TASK-2
| `ods-go-toolset` contaner image
| Container image for building Go applications. Based on `ubi8` (SDS-EXT-1), includes SDS-EXT-3, SDS-EXT-4,EXT- SDS-EXT-5, SDS-EXT-6, SDS-EXT-9, SDS-SHARED-3, SDS-TASK-3 and SDS-TASK-25.

| SDS-TASK-3
| `build-go.sh` shell script
a| Runs `gofmt` (SDS-EXT-3) to check all Go files are formatted.

Runs `golangci-lint` (SDS-EXT-4) to check if there are any lint errors.

If the `pre-test-script` is set, it executes the given script before running tests.

Runs `go test`, excluding the `vendor` directory, creating code coverage and xUnit report (using SDS-EXT-5). The artifacts are placed in the working directory and in `.ods/artifacts/code-coverage` and `.ods/artifacts/xunit-reports`, respectively. If the artifacts are already found in `.ods/artifacts`, then testing is skipped and the artifacts are copied to the working directory to expose them to SonarQube.

Builds Go application (using SDS-EXT-3, optionally SDS-EXT-6) into specified output directory.

Supplies default SonarQube project properties file if required (SDS-SHARED-3).

| SDS-TASK-25
| `go.properties` properties file
| Default configuration for Go SonarQube project.
|===

===== `ods-build-gradle` task

[cols="1,1,3"]
|===
| SDS-TASK-4
| `ods-build-gradle` ClusterTask resource
a| The task defines two steps:

. Build Gradle module  (referencing SDS-TASK-5 and executing SDS-TASK-6)
. Analyze source code (referencing SDS-SHARED-1 and executing SDS-SHARED-2)

Input parameters:

* `working-dir`: allows to customize which directory is used as the Gradle module root. If set, artifacts are prefixed with `<SUBDIRECTORY>-`, and the SQ project is suffixed with `-<SUBDIRECTORY>`.
* `gradle-additional-tasks`: additional gradle tasks to be passed to the gradle build
* `gradle-options`: options to be passed to the gradle build
* `output-dir`: sets destination directory of built binary
* `sonar-quality-gate`: enables quality gate check
* `sonar-skip`: skips SonarQube analysis

| SDS-TASK-5
| `ods-gradle-toolset` contaner image
| Container image for building Gradle modules. Based on `ubi8/openjdk-17` (SDS-EXT-11), includes SDS-EXT-12, SDS-SHARED-3, SDS-TASK-6 and SDS-TASK-26.

| SDS-TASK-6
| `build-gradle.sh` shell script
a| Builds a Gradle module that provides a gradle build script into `docker/app.jar`.

The destination directory can be changed by exporting the environment variable `ODS_OUTPUT_DIR`.

Runs `gradlew clean build` to build the Gradle module, using optionas and additional tasks as passed from SDS-TASK-4.

Generated unit test reports are placed in the working directory (for SonarQube to pick them up) and copied into `.ods/artifacts/xunit-reports`.

Generated unit test coverage report are placed in the working directory (for SonarQube to pick them up) and copied into `.ods/artifacts/code-coverage`.

Supplies default SonarQube project properties file if required (SDS-SHARED-3).

| SDS-TASK-26
| `gradle.properties` properties file
| Default configuration for Gradle SonarQube project.
|===

===== `ods-start` task

[cols="1,1,3"]
|===
| SDS-TASK-7
| `ods-start` ClusterTask resource
a| Task to start pipeline. References SDS-TASK-8 and executes SDS-TASK-9.

Input parameters: TODO

| SDS-TASK-8
| `ods-start` contaner image
| Container image to start a pipeline. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes SDS-EXT-9, SDS-EXT-13, SDS-EXT-22 and SDS-TASK-9.

| SDS-TASK-9
| `start` binary
a| The task checks out the repository of given URL and Git ref into the mounted workspace, cleaning any previous contents. If the checked out `ods.y(a)ml` configures any child repositories, those are checked out as well from the configured URL and Git ref. All checkouts are shallow and include submodules.

Context information is stored under `.ods` for each checked out repository:

* repository related information: project key, component key, repository name, Git URL, Git (full) ref, Git commit SHA, pull request base and pull request key.
* OpenShift related information: namespace
* deployment related information: version and environment

Any artifacts in Nexus belonging to the same commit being built are downloaded and placed into the respective `.ods/artifacts` folder of each checked out repository.

The Bitbucket build status of the commit being built is set to "in progress". The build status links back to the pipeline run.

If any child repository is missing a successful pipeline run artifact for the checked out commit, the task fails.
|===

===== `ods-finish` task

[cols="1,1,3"]
|===
| SDS-TASK-10
| `ods-finish` ClusterTask resource
a| Task to finish pipeline. References SDS-TASK-11 and executes SDS-TASK-12.

Input parameters: TODO

| SDS-TASK-11
| `ods-finish` contaner image
| Container image to start a pipeline. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes SDS-TASK-12.

| SDS-TASK-12
| `finish` binary
a| Sets the Bitbucket build status to "failed" or "successful", depending on whether all tasks succeeded or not. The build status links back to the pipeline run.

Creates an artifact for the pipeline run, containing its name and status, provided that all tasks succeeded.

Uploads all files in any `.ods/artifacts` folder to Nexus, storing them in a group named `/<PROJECT>/<REPOSITORY>/<GIT-COMMIT-SHA>`, provided that all tasks succeeded.
|===

===== `ods-build-python` task

[cols="1,1,3"]
|===
| SDS-TASK-13
| `ods-build-python` ClusterTask resource
a| The task defines two steps:

. Build Python applications (referencing SDS-TASK-14 and executing SDS-TASK-15)
. Analyze source code (referencing SDS-SHARED-1 and executing SDS-SHARED-2)

Input parameters: TODO

| SDS-TASK-14
| `ods-python-toolset` contaner image
| Container image to build Python applications. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes SDS-EXT-14, SDS-EXT-15, SDS-SHARED-3, SDS-TASK-15 and SDS-TASK-27.

| SDS-TASK-15
| `build-python.sh` shell script
a| Runs `mypy` and `flake8` to lint source code and fails if there are any findings. The maximum allowed line length defaults to 120 can be set by the `max-line-length` task parameter.

If the `pre-test-script` is set, it executes the given script before running tests.

Runs `pytest`, creating code coverage and xUnit reports. The artifacts are placed in the working directory and in `.ods/artifacts/code-coverage` and `.ods/artifacts/xunit-reports`, respectively.

Builds Python application (using SDS-EXT-14) into the directory specified by `output-dir`.

Supplies default SonarQube project properties file if required (SDS-SHARED-3).

| SDS-TASK-27
| `python.properties` properties file
| Default configuration for Python SonarQube project.
|===

[cols="1,1,3"]
|===
| SDS-TASK-16
| `ods-build-typescript` ClusterTask resource
a| The task defines two steps:

. Build TypeScript applications (referencing SDS-TASK-17 and executing SDS-TASK-18)
. Analyze source code (referencing SDS-SHARED-1 and executing SDS-SHARED-2)

Input parameters: TODO

| SDS-TASK-17
| `ods-node16-typescript-toolset` container image
| Container image to build TypeScript applications. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes SDS-EXT-6, SDS-EXT-16, SDS-SHARED-3, SDS-TASK-18 and SDS-TASK-28.

| SDS-TASK-18
| `build-typescript.sh` shell script
a| Runs `npm run build`, and copies the `dist` folder into the directory specified by `output-dir`.

Runs `npm run test`, creating code coverage and xUnit reports. The artifacts are placed in the working directory and in `.ods/artifacts/code-coverage` and `.ods/artifacts/xunit-reports`, respectively.

Supplies default SonarQube project properties file if required (SDS-SHARED-3).

| SDS-TASK-28
| `typescript.properties` properties file
| Default configuration for TypeScript SonarQube project.
|===

==== `ods-package-image` task

[cols="1,1,3"]
|===
| SDS-TASK-19
| `ods-package-image` ClusterTask resource
| Builds and scans a container image, then pushes it to a registry. References SDS-TASK-20 and executes SDS-TASK-21.

| SDS-TASK-20
| `ods-buildah` contaner image
| Container image to build, scan and push images. Based on `ubi8` (SDS-EXT-1), includes SDS-EXT-17, SDS-EXT-18 and SDS-TASK-21. If the build argument `aquasecScannerUrl` is set, the referenced Aqua Scanner binary is installed into the image as well.

| SDS-TASK-21
| `build-and-push` binary
a| Checks if an image with the tag to built exist already in the target registry, and if so, skips the build.

Builds a container image using SDS-EXT-18:

* The Docker context directory defaults to `docker` and can be overwritten by the `docker-dir` parameter.
* The Dockerfile defaults to `Dockerfile`, and can be overwritten by `dockerfile` parameter. The location is relative to the Docker context directory.
* The resulting image name and SHA is placed into `.ods/artifacts`.

Pushes the image to the target registry (defaulting to an image stream in the namespace of the pipeline run) using SDS-EXT-17.

If the Aqua scanner is installed in the base image, the  pushed image shall be scanned. The resulting report is placed in `.ods/artifacts` and attached as a code insight to Bitbucket.
|===

==== `ods-deploy-helm` task

[cols="1,1,3"]
|===
| SDS-TASK-22
| `ods-deploy-helm` ClusterTask resource
| Deploys a Helm chart and promotes images. References SDS-TASK-23 and executes SDS-TASK-24.

| SDS-TASK-23
| `ods-helm` contaner image
| Container image to promote images and deploy Helm charts. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes SDS-EXT-9, SDS-EXT-15, SDS-EXT-17, SDS-EXT-19, SDS-EXT-20, SDS-EXT-21, SDS-EXT-23, SDS-EXT-24 and SDS-TASK-24.

| SDS-TASK-24
| `deploy-with-helm` binary
a| Skips when no `environment` is given.

Pushes images into the target namespace.

* The images that are pushed are determined by the artifacts in `.ods/artifacts/image-digests`. Each artifact contains information from which registry / image stream to get the images.
* The target namespace is selected from the given `environment`.
* The target registry may also be external to the cluster in which the pipeline runs. The registry is identified by the `registryHost` field of the environment configuration, and the credential token of `apiCredentialsSecret` is used to authenticate.

Upgrades (or installs) a Helm chart.

* The Helm chart is expected at the location identified by the `chartDir` parameter (defaulting to `chart`).
* The task errors if no chart can be found.
* A diff is performed before the upgrade/install. If there are no differences, upgrade/install is skipped.
* The upgrade/install waits until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful.
* Any values and secrets files corresponding to the environment and stage are respected (`values.yaml`, `secrets.yaml`, `values.<STAGE>.yaml`, `secrets.<STAGE>.yaml`, `values.<ENVIRONMENT>.yaml`, `secrets.<ENVIRONMENT>.yaml`; in that order of specificity).
* A values file containing the Git commit SHA is auto-generated and added to the Helm diff/upgrade invocation.
* Any encrypted secrets files are decrypted on the fly, using the age key provided by the `Secret` identified by the `age-key-secret` parameter (defaulting to `helm-secrets-age-key`). The secret is expected to expose the age key under the `key.txt` field.
* The "app version" is set to the Git commit SHA and the "version" is set to given `version` if any, otherwise the chart version in `Chart.yaml`.
* Charts in any of the respositories configured in `ods.y(a)ml` are packaged according to the same rules and added as subcharts.
* The target namespace may also be external to the cluster in which the pipeline runs. The API server is identified by the `apiServer` field of the environment configuration, and the credential token of `apiCredentialsSecret` is used to authenticate.
|===

==== Local ODS Pipeline Installation

===== Webhook Interceptor

[cols="1,1,3"]
|===
| SDS-INTERCEPTOR-1
| `ods-pipeline` Service resource
| Service (exposing a set of pods) for the webhook interceptor

| SDS-INTERCEPTOR-2
| `ods-pipeline` Deployment resource
| Deployment (providing declarative updates for pods and replica sets) for the webhook interceptor. The container template references SDS-INTERCEPTOR-3.

| SDS-INTERCEPTOR-3
| `ods-webhook-interceptor` container image
| Container image to intercept Tekton Trigger events coming from Bitbucket webhooks. Based on `ubi8/ubi-minimal` (SDS-EXT-2), includes SDS-INTERCEPTOR-4.

| SDS-INTERCEPTOR-4
| `webhook-interceptor` binary
a| The interceptor parses the JSON payload and handles `repo:refs_changed` and `pr:opened` events. Other events are dropped.

For Git commits which message instructs to skip CI, no pipelines are triggererd. Instructions may be anywhere in the commit message and may be one of (case insensitive):

```
[ci skip]
[skip ci]
***NO_CI***
```

A pipeline is created or updated corresponding to the Git branch received in the webhook request. The pipeline name is made out of the component and the sanitized branch. A maximum of 63 characters is respected. Tasks (including `finally` tasks) of the pipline are read from the ODS config file in the repository.
|===

===== Artifact Download

[cols="1,1,3"]
|===
| SDS-DLD-1
| `artifact-download` binary
a| The binary receives flags from the user identifying:

* OpenShift namespace
* Git repository (project/repository)
* Git tag

The OpenShift namespace is used to retrieve configuration and secrets required to communicate with Bitbucket and Nexus. The `ods.yaml` of the Git repository is retrieved at given Git tag to detect any subrepositories. If the given tag is `WIP`, the repository information is not retrieved from Bitbucket but located from the `.git` directory in the working directory.

For all repositories in scope, the artifacts in the corresponding groups in Nexus are downloaded to the local host. The files are placed into `artifacts-out/<TAG>` (customizable via `--output`).
|===


=== Third-party components

[cols="1,1,1,2,1"]
|===
|ID |Name |Version |Description |Link

| SDS-EXT-1
| Red Hat Universal Base Image 8
| 8.4
| Universal Base Image is designed and engineered to be the base layer for a wide range of applications, middleware and utilities. It is maintained by Red Hat and updated regularly.
| https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e

| SDS-EXT-2
| Red Hat Universal Base Image 8 Minimal
| 8.4
| Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. It is maintained by Red Hat and updated regularly.
| https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8

| SDS-EXT-3
| Go
| 1.16
| Go toolchain.
| https://golang.org

| SDS-EXT-4
| golangci-lint
| 1.41
| golangci-lint is a Go linters aggregator.
| https://golangci-lint.run

| SDS-EXT-5
| junit-report
| 0.9
| Converts go test output to an xml report, suitable for applications that expect junit xml reports.
| https://github.com/jstemmer/go-junit-report

| SDS-EXT-6
| gcc/gcc-c++
| 8.5
| Optimizing compiler supporting various programming languages, required for CGO.
| https://foo

| SDS-EXT-7
| sonar-scanner
| 3.1
| General purpose SonarQube scanner
| https://github.com/SonarSource/sonar-scanner-cli

| SDS-EXT-8
| cnes-report
| 3.2
| Exports code analysis from a SonarQube server in various file formats.
| https://github.com/cnescatlab/sonar-cnes-report

| SDS-EXT-9
| Git
| 2.27
| Distributed version control system.
| https://git-scm.com

| SDS-EXT-10
| OpenJDK Headless
| 17
| Reference implementation of version 17 of the Java SE Platform.
| https://openjdk.java.net/projects/jdk/17/

| SDS-EXT-11
| Red Hat OpenJDK 17 Image
| 1.10
| OpenJDK 17 container is a base platform for building and running plain Java 17 applications, e.g. fat-jar and flat classpath.
| https://catalog.redhat.com/software/containers/ubi8/openjdk-17/618bdbf34ae3739687568813

| SDS-EXT-12
| Gradle
| 7.2
| Build automation tool for multi-language software development.
| https://gradle.org

| SDS-EXT-13
| openssh-clients
| 8.0
| Clients necessary to make encrypted connections to SSH servers.
| https://gradle.org

| SDS-EXT-14
| Python
| 3.9
| Interpreted high-level general-purpose programming language.
| https://www.python.org

| SDS-EXT-15
| Tar
| 1.30
| Used to create and extract archive files.
| https://www.gnu.org/software/tar/

| SDS-EXT-16
| Node.js
| 16
| Back-end JavaScript runtime environment.
| https://nodejs.org/

| SDS-EXT-17
| Skopeo
| 1.4
| Tool for moving container images between different types of container storages.
| https://github.com/containers/skopeo

| SDS-EXT-18
| Buildah
| 1.22
| Tool that facilitates building OCI images.
| https://github.com/containers/buildah

| SDS-EXT-19
| Helm
| 3.5
| Package manager for Kubernetes.
| https://helm.sh

| SDS-EXT-20
| Helm Diff plugin
| 3.1
| Shows a diff explaining what a helm upgrade would change.
| https://github.com/databus23/helm-diff

| SDS-EXT-21
| Helm Secrets plugin
| 3.10
| Manages secrets with Git workflow.
| https://github.com/jkroepke/helm-secrets

| SDS-EXT-22
| Tekton
| 0.24
| Cloud-native Pipeline resource.
| https://github.com/tektoncd/pipeline

| SDS-EXT-23
| Sops
| 3.7
| Encrypted files management tool.
| https://github.com/mozilla/sops

| SDS-EXT-24
| Age
| 1.0
| File encryption tool, format and Go library with small explicit keys.
| https://github.com/FiloSottile/age

|===

== Appendix

N/A

== Document History

The following table provides the history of the document.

[cols="1,1,1,3"]
|===
| Version | Date | Author | Change

| 0.7
| 2021-12-20
| Henning Groß
| Updated Node.js version.

| 0.6
| 2021-12-15
| Andreas Kübler
| Updated JDK version.

| 0.5
| 2021-12-10
| Michael Sauter
| Add default SonarQube project properties.

| 0.4
| 2021-12-09
| Gerard Castillo
| Add Sops and Age, and updated Helm Secrets plugin.

| 0.3
| 2021-11-26
| Gerard Castillo
| Updated python.

| 0.2
| 2021-11-10
| Michael Sauter
| Updated gcc, skopeo and buildah.

| 0.1
| 2021-10-01
| Michael Sauter
| Initial version.
|===
