/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ods.java.gradle.sample.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// this class exists to have more than one test xml in the end
class AppTest2 {
    @Test void appHasAGreetingTwo() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
