@startuml "namespaced-installation"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

LAYOUT_LEFT_RIGHT()

Container_Boundary(c1, "Namespaced ODS Pipeline Installation"){
    Boundary(config, "Configuration & Management") {
        Component(route, "Route", "Route resource", "External endpoint for Bitbucket webhook")
        Component(ods_pipeline_manager, "ODS Pipeline Manager", "Custom service", "Manage pipelines")
        Component(config_maps, "Config Maps", "ConfigMap resources", "Configuration for consumption by pipelines")
        Component(secrets, "Secrets", "Secret resources", "Secret for consumption by pipelines")
    }

    Boundary(tasks, "Tasks") {
        Component(task_start, "ods-pipeline-start", "Task", "Starts pipeline run (checkout repository, set build status, download artifacts, ...)")
        Component(task_finish, "ods-pipeline-finish", "Task", "Finishes pipeline run (set build status, upload artifacts, ...)")
    }

    Boundary(images, "Images") {
        Component(image_start, "ods-pipeline/start", "Container Image", "Git, start script")
        Component(image_finish, "ods-pipeline/finish", "Container Image", "Finish script")
        Component(image_pipeline_manager, "ods/pipeline-manager", "Container Image", "Webhook receiver and pipeline manager")
    }

}

Rel(ods_pipeline_manager, route, "exposed via")

config_maps -[hidden]- secrets

@enduml
