@startuml "trigger-architecture"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person_Ext(developer, "Developer")

System_Boundary(c1, "OpenShift"){
    
    Container(route, "Route", "External endpoint for Bitbucket webhook")

    Container(ods_service, "ODS Pipeline Manager", "Service", "Manage and trigger pipelines")

    Container(pipeline_run, "PipelineRun", "Tekton-provided resource", "References tasks defined in Git repo")
}

System_Ext(bitbucket_repo, "Bitbucket Repository")

Rel(developer, bitbucket_repo, "Pushes", "Git commit")

Rel(bitbucket_repo, route, "Send webhook request")

Rel(route, ods_service, "Forward", "event")

Rel(ods_service, bitbucket_repo, "Download ods.y(a)ml")

Rel(ods_service, pipeline_run, "Create")

Lay_D(developer, bitbucket_repo)

@enduml
