kind: ConfigMap
apiVersion: v1
metadata:
  name: ods-aqua
  labels:
    {{- include "chart.labels" . | nindent 4}}
data:
  url: '{{.Values.aquaUrl | trimSuffix "/"}}'
  registry: '{{.Values.aquaRegistry}}'
