kind: ConfigMap
apiVersion: v1
metadata:
  name: ods-bitbucket
  labels:
    {{- include "chart.labels" . | nindent 4}}
data:
  url: '{{.Values.bitbucketUrl | trimSuffix "/"}}'
  repoBase: '{{.Values.bitbucketUrl | trimSuffix "/"}}/scm'
