apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ods-finish
spec:
  description: Finishes the pipeline
  params:
    - description: name of pipeline run
      name: pipeline-run-name
      type: string
    - name: aggregate-tasks-status
      description: The aggregate status of all the tasks.
      default: "None"
  steps:
    - name: ods-finish
      image: build/package/Dockerfile.finish
      env:
        - name: NEXUS_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-nexus
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: ods-nexus-auth
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-nexus-auth
        - name: BITBUCKET_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-bitbucket
        - name: BITBUCKET_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-bitbucket-auth
        - name: CONSOLE_URL
          valueFrom:
            configMapKeyRef:
              key: consoleUrl
              name: ods-cluster
      resources: {}
      workingDir: $(workspaces.source.path)
      script: |

        # ods-finish is built from cmd/finish/main.go.
        ods-finish \
          -pipeline-run-name=$(params.pipeline-run-name) \
          -aggregate-tasks-status=$(params.aggregate-tasks-status)

  workspaces:
    - description: The git repo will be present onto the volume backing this workspace
      name: source
