apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ods-build-image
spec:
  description: |
    Packages applications into container images using buildah.

    buildah builds a container image from the `docker-dir` directory using the
    provided `dockerfile`.

    By default, the image is named after the component and pushed into the image
    stream located in the namespace of the pipeline run.
  params:
    # Order of parameters matters as the "registry" param is replaced by a kustomization patch.
    - name: registry
      description: Image registry to push image to.
      type: string
      default: 'image-registry.openshift-image-registry.svc:5000'
    - name: image-stream
      description: Reference of the image stream buildah will produce. If not set, the value of `.ods/component` is used.
      type: string
      default: ''
    - name: storage-driver
      description: Set buildah storage driver.
      type: string
      default: vfs
    - name: dockerfile
      description: Path to the Dockerfile to build (relative to `docker-dir`).
      type: string
      default: ./Dockerfile
    - name: docker-dir
      description: Path to the directory to use as Docker context.
      type: string
      default: docker
    - name: tls-verify
      description: >-
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry).
      type: string
      default: 'true'
    - name: format
      description: 'The format of the built container, `oci` or `docker`.'
      type: string
      default: oci
    - name: buildah-build-extra-args
      description: Extra parameters passed for the build command when building images.
      type: string
      default: ''
    - name: buildah-push-extra-args
      description: Extra parameters passed for the push command when pushing images.
      type: string
      default: ''
  results:
    - description: Digest of the image just built.
      name: image-digest
  steps:
    - name: build-and-push-image
      image: build/package/Dockerfile.buildah
      resources: {}
      script: |

        odsNamespace=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)

        odsGitCommit=$(cat .ods/git-commit-sha)

        imageStreamParam="$(params.image-stream)"
        imageStream=${imageStreamParam:-$(cat .ods/component)}

        set +e

        imageDigest=$(skopeo inspect \
          --format '{{.Digest}}' \
          --tls-verify=$(params.tls-verify) \
          docker://$(params.registry)/$odsNamespace/$imageStream:$odsGitCommit)

        if [ "$?" = "0" ]; then
          set -e
          echo "Image exists already"
          mkdir -p /tekton/results
          echo $imageDigest > /tekton/results/image-digest
        else
          set -e
          image="$(params.registry)/$odsNamespace/$imageStream:$odsGitCommit"

          buildah --storage-driver=$(params.storage-driver) bud \
            $(params.buildah-build-extra-args) --format=$(params.format) \
            --tls-verify=$(params.tls-verify) --no-cache \
            -f $(params.dockerfile) -t $image $(params.docker-dir)

          buildah --storage-driver=$(params.storage-driver) push \
            $(params.buildah-push-extra-args) --tls-verify=$(params.tls-verify) \
            --digestfile $(workspaces.source.path)/image-digest $image \
            docker://$image
          
          mkdir -p /tekton/results
          cat $(workspaces.source.path)/image-digest | tee /tekton/results/image-digest
        fi

        mkdir -p $(workspaces.source.path)/.ods/artifacts/image-digests
        echo "{\"image\":\"${image}\", \"registry\":\"$(params.registry)\", \"repository\":\"${odsNamespace}\", \"name\":\"${imageStream}\", \"tag\":\"${odsGitCommit}\", \"digest\":\"$(cat /tekton/results/image-digest)\"}" > $(workspaces.source.path)/.ods/artifacts/image-digests/$imageStream.json
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: $(workspaces.source.path)
  volumes:
    - emptyDir: {}
      name: varlibcontainers
  workspaces:
    - name: source
