apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ods-deploy-helm
spec:
  description: |
    Deploy Helm charts.

    This tasks will install / upgrade a Helm chart into your Kubernetes /
    OpenShift cluster using Helm.

    Helm has the plugins `helm-diff` and `helm-secrets` installed. A diff is performed
    before an upgrade is attempted. `helm-secrets` can be used to encrypt sensitive
    values in the underlying Git repository.

    Based on the target environment, some values files are added automatically to the
    invocation of the `helm` command if they are present:

    - `values.<STAGE>.yaml`: a values file named after the stage (`dev`, `qa` or `prod`) of the target environment.
    - `values.<ENVIRONMENT>.yaml`: a values file named after the name of the target environment.

    Further, the task adds a `values.generated.yaml` file. This values file
    contains only one value, `gitCommitSha`, which contains the Git commit SHA being built. It is
    provided by the task as this value cannot be known by value file authors in advance. Use this
    value to set e.g. the image tags in `Deployment` resources, like this: `{{ .Values.gitCommitSha }}`.

    Before the Helm chart is applied, it is packaged, setting the `appVersion` to the Git commit SHA
    and the `version` to the externally provided version, if any. If `version` is not given, the value
    in `Chart.yaml` is used as-is.

    If the pipeline runs for a repository defining subrepos in its `ods.yml` file, then any charts in
    those subrepos are packaged as well, and added as dependencies to the top-most chart under `charts/`.
  params:
    - name: chart-dir
      description: Helm chart directory that will be deployed
      type: string
      default: ./chart
    - name: release-name
      description: The Helm release name. If empty, the release name is simply the name of the chart.
      type: string
      default: ''
    - name: environment
      description: The name of the environment to deploy to
      type: string
      default: dev
    - name: target
      description: The name of the target to deploy into
      type: string
      default: default
    - name: overwrite-values
      description: >-
        Specify the values you want to overwrite, comma separated.
        Example: `autoscaling.enabled=true,replicas=1`
      type: string
      default: ''
  steps:
    - name: helm-upgrade-from-repo
      image: build/package/Dockerfile.helm
      resources: {}
      script: |
        # deploy-with-helm is built from /cmd/deploy-with-helm/main.go.
        deploy-with-helm \
          -chart-dir=$(params.chart-dir) \
          -release-name=$(params.release-name) \
          -environment=$(params.environment) \
          -target=$(params.target)
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
