apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ods-deploy-helm
spec:
  description: >-
    These tasks will install / upgrade a helm chart into your Kubernetes /
    OpenShift Cluster using Helm
  params:
    - default: ./chart
      description: Specify chart dir that will be deployed
      name: chart-dir
      type: string
    - default: ''
      description: The helm release name
      name: release-name
      type: string
    - default: ''
      description: The namespace of the pipeline
      name: namespace
      type: string
    - default: dev
      description: The environment to deploy to
      name: environment
      type: string
    - default: default
      description: The target to deploy into
      name: target
      type: string
    - default: ''
      description: Project
      name: project
      type: string
    - default: ''
      description: Repository
      name: repository
      type: string
    - default: ''
      description: >-
        Specify the values you want to overwrite, comma separated:
        autoscaling.enabled=true,replicas=1
      name: overwrite-values
      type: string
  steps:
    - name: helm-upgrade-from-repo
      image: build/package/Dockerfile.helm
      resources: {}
      script: |
        # deploy-with-helm is built from /cmd/deploy-with-helm/main.go.
        deploy-with-helm \
          -chart-dir=$(params.chart-dir) \
          -release-name=$(params.release-name) \
          -environment=$(params.environment) \
          -target=$(params.target)
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
