{{if or .Values.global.enabledTasks.buildTypescript .Values.node16TypescriptToolset}}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-node16-typescript-toolset
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-node16-typescript-toolset:{{.Values.global.imageTag | default .Chart.AppVersion}}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: imageTag
          value: '{{.Values.global.imageTag | default .Chart.AppVersion}}'
  source:
    dockerfile: |-
      {{- .Files.Get "docker/Dockerfile.node16-typescript-toolset" | nindent 6}}
  runPolicy: Serial
{{end}}
