{{if or .Values.global.enabledTasks.packageImage .Values.packageImage}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-package-image
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
