{{if or .Values.global.enabledTasks.packageImage .Values.buildah}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-buildah
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
