{{if or .Values.global.enabledTasks.deployHelm .Values.helm}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-helm
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
