{{if or .Values.global.enabledTasks.buildNPM .Values.node16NPMToolset}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-node16-npm-toolset
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
