{{if or .Values.global.enabledTasks.buildSbt .Values.sbtToolset}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-sbt-toolset
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
