{{if or .Values.global.enabledTasks.buildGo .Values.goToolset}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-go-toolset
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
