{{if or .Values.global.enabledTasks.buildPython .Values.pythonToolset }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-python-toolset
  labels:
    {{- include "chart.labels" . | nindent 4}}
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
