{{if default true .Values.autoBuild}}
apiVersion: batch/v1
kind: Job
metadata:
  name: ods-start-builds
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: pipeline
      restartPolicy: Never
      containers:
      - name: post-upgrade-job
        image: '{{.Values.autoBuildImage | default "quay.io/openshift/origin-cli:4.10"}}'
        command: ["/bin/sh","-c"]
        args: ["set -e; oc get bc -l=app.kubernetes.io/name=ods-pipeline -o=name | xargs -I % sh -c 'oc start-build %'"]
{{end}}
