kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-python-toolset
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "ods-python-toolset:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: build/package/Dockerfile.python-toolset
      from:
        kind: DockerImage
        name: "registry.redhat.io/ubi8"
      pullSecret:
        name: registry.redhat.io
  postCommit: {}
  source:
    type: Git
  runPolicy: Serial
