kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-finish
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-finish:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: build/package/Dockerfile.finish
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi8/ubi-micro'
      pullSecret:
        name: registry.redhat.io
  postCommit: {}
  source:
    type: Git
  runPolicy: Serial
