= Artifacts

Pipelines create artifacts based on the source code they work on. Artifacts are stored in Nexus. Artifacts used in released software versions need to be archived for a long time and must not be overwritable. Artifacts should be associated with the Git SHA from which they were created.

== Artifact files

* xUnit files
* BDD test reports (?)
* code coverage reports
* static analysis reports
* static analysis issues
* image scan / dependency vulnerability scan results
* image manifests
* Pipeline logs
* Helm charts
* ?

== Handling

Pipelines write artifacts into `.ods/artifacts/<TYPE>/<ARTIFACT>`. This folder is uploaded to the Nexus repository specified by the `artifact-target` parameter in the final task. If a pipeline starts, the Nexus repository specified by the `artifact-source` parameter is searched for artifacts for the current revision and any results are placed into `.ods/artifacts`.

Some activities inside tasks/steps may be skipped depending on existing artifacts (e.g. no need to re-build image if manifest exists, etc.).
