= Creating an ODS Task

Creating a technology-specific ODS Task consists of a few steps like creating a Dockerfile, OpenShift resources, the Tekton Task itself and more.

Run `make generate-ods-task-files technology=<technology>` to create the minimum number of necessary files to get started.

For instance, if you were to generate a dotnet ODS Task, you could easily get started running:

```
$ make generate-ods-task-files technology=dotnet
go run cmd/ods-task-generator/main.go dotnet
Creating file deploy/central/images/bc-ods-build-dotnet.yml
Creating file deploy/central/images/is-ods-build-dotnet.yml
Creating file deploy/central/tasks/task-ods-build-dotnet.yml
Creating file build/package/Dockerfile.dotnet
Creating file build/package/scripts/build-dotnet.sh
Appending file deploy/central/images/kustomization.yaml
Appending file deploy/central/tasks/kustomization.yaml
You're all set to write contribute with your technofmty-specific ODS Task.
Now to create a sample application that will be used to test the Task under test/testdata/workspaces/.
Once you're done implementing and testing your Task, review the checklist in docs/creating-an-ods-task.adoc to make sure you're not missing anything.
```

== Checklist

To create a technology-specific Task (e.g. python), the following files should be **added**:

- [ ] build/package/Dockerfile.python-toolset - The Dockerfile with the dependencies and runtime.
- [ ] build/package/scripts/build-python.sh - Bash script to carry out the build, linting, testing operations. 
- [ ] deploy/central/images/bc-ods-build-python.yml - BuildConfig to generate the ods-build-python image.
- [ ] deploy/central/images/is-ods-build-python.yml - Create ImageStream resource in OpenShift.
- [ ] deploy/central/images/kustomization.yaml - Add `bc-ods-build-python.yaml` and `is-ods-build-python.yaml` to the resources.
- [ ] deploy/central/tasks/kustomization.yaml - Add `task-ods-build-python.yaml` to the resources.
- [ ] deploy/central/tasks/task-ods-build-python.yml - The Tekton Task.
- [ ] docs/tasks/task-ods-build-python.adoc - To describe the task and its parameters.
- [ ] test/tasks/ods-build-python_test.go - A test file to test the behavior of the Tekton Task.
- [ ] test/testdata/workspaces/python-flask-sample-app - Sample application that will be used to test the Task.

The following files should be **updated**:

- [ ] .github/workflows/main.yml - Build ods python image and push it to the internal registry.

// TODO: Elaborate more on how to test a Task
