:toc:

= Getting Started

This guide explains how you can start to use ODS pipeline in your project. It is assumed you have read the link:introduction.adoc[introduction] and have aleady link:user-installation.adoc[installed] ODS pipeline in an OpenShift project.

The guide will look at two scenarios:

* converting an existing, ODS quickstarter based component from Jenkins to `ods-pipeline`
* creating an `ods-pipeline`-enabled repository from scratch

== Converting an existing component from Jenkins to `ods-pipeline`

In this scenario, you have already provisioned an link:https://github.com/opendevstack/ods-quickstarters[ODS quickstarter]. Let's assume that you have selected the Go quickstarter and have a repository named `foo-backend` in your Bitbucket project. Other quickstarters are converted following the same steps, simply adjust the instructions below.

Let's start by looking at the repository in detail. A few files are of special interest for this exercise:

* `Jenkinsfile`: describes the Jenkins pipeline to run
* `docker/Dockerfile`: describes the container image to build

You will need to replace the `Jenkinsfile` with an `ods.yaml` file. The `Jenkinsfile` defines which branches are mapped to which environment and uses stages provided by the link:https://github.com/opendevstack/ods-jenkins-shared-library[ODS Jenkins Shared Library] as well as custom Go tool instructions to build and deploy your application. The file might look like this:

.Jenkinsfile
[source,groovy]
----
@Library('ods-jenkins-shared-library@4.x') _

odsComponentPipeline(
  imageStreamTag: 'ods/jenkins-agent-golang:4.x',
  branchToEnvironmentMapping: [
    'master': 'dev',
  ]
) { context ->
  odsComponentStageImportOpenShiftImageOrElse(context) {
    stageCheckFormat(context)
    stageLint(context)
    stageUnitTest(context)
    stageBuild(context)
    odsComponentStageScanWithSonar(context)
    odsComponentStageBuildOpenShiftImage(context)
  }
  odsComponentStageRolloutOpenShiftDeployment(context)
}

def stageCheckFormat(def context) {
  stage('Check Format') {
    def unformatted = sh(script: 'gofmt -l .', returnStdout: true)
    if (unformatted) {
      println "Unformatted files:\n${unformatted}"
      error 'All files need to be gofmt\'d. Please run: gofmt -w .'
    }
  }
}

def stageLint(def context) {
  stage('Lint') {
    withEnv(["CGO_ENABLED=0", "GOCACHE=${WORKSPACE}/.cache"]) {
      sh "golangci-lint run"
    }
  }
}

def stageBuild(def context) {
  stage('Build') {
    def binary = "app_linux_amd64"
    withEnv(["CGO_ENABLED=0", "GOCACHE=${WORKSPACE}/.cache"]) {
      sh "go build -o docker/${binary}"
    }
  }
}

def stageUnitTest(def context) {
  stage('Unit Test') {
    withEnv(["CGO_ENABLED=0", "GOCACHE=${WORKSPACE}/.cache"]) {
      sh 'mkdir -p build/test-results/test'
      def gopkgs = sh(script: 'go list ./... | grep -v /vendor', returnStdout: true).trim()
      withEnv(["GOPKGS=${gopkgs}"]) {
        def status = sh(script: 'go test -v -coverprofile=coverage.out $GOPKGS 2>&1 > test-results.txt', returnStatus: true)
        sh 'cat test-results.txt | go-junit-report > build/test-results/test/report.xml'
        if (status != 0) {
          error "go test failed!"
        }
      }
    }
  }
}
----

Compared to Jenkins, you cannot define any scripts directly in the `ods.yaml` file describing your Tekton pipeline. You may only reference existing tasks and adjust their parameters. As a consequence, the build related stages (`stageCheckFormat`, `stageLint`, `stageUnitTest`, `stageBuild`) are provided by a cluster task (named `ods-build-go-vX`) instead.

An equivalent `ods.yaml` for the above `Jenkinsfile` looks like this:

.ods.yaml
[source,yaml]
----
branchToEnvironmentMapping:
- branch: master
  environment: dev

environments:
- name: dev
  namespace: foo-dev
  stage: dev

pipeline:
  tasks:
  - name: backend-build-go
    taskRef:
      kind: ClusterTask
      name: ods-build-go-v0-1-1
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: backend-package-image
    taskRef:
      kind: ClusterTask
      name: ods-package-image-v0-1-1
    runAfter:
    - backend-build-go
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: backend-deploy
    taskRef:
      kind: ClusterTask
      name: ods-deploy-helm-v0-1-1
    runAfter:
    - backend-package-image
    workspaces:
    - name: source
      workspace: shared-workspace
----

What has been done in Jenkins in `stageCheckFormat`, `stageLint`, `stageUnitTest`, `stageBuild` and `odsComponentStageScanWithSonar` is now done by the `ods-build-go-v0-1-1` task. If you have modified how the application is tested and built, or added further steps, you will need to create your own Tekton tasks reflecting those changes. See the link:authoring-tasks.adoc[authoring tasks] guide.

Building the container image is now done in `ods-package-image-v0-1-1` instead of in `odsComponentStageBuildOpenShiftImage`. The task continues to use the existing `docker/Dockerfile` file, which does not need to change much if at all. Consult the task reference in question for more information. In the case of Go, the link:tasks/ods-build-go.adoc[`ods-build-go` task reference] states that the resulting Go binary is named `app` and placed into the `docker` directory. Make sure that your `docker/Dockerfile` copies `app`, not e.g. `app_linux_amd64` (as is the default for an ODS 4.x based Go quickstarter).

Finally, the application is deployed in `ods-deploy-helm-v0-1-1` as opposed to `odsComponentStageRolloutOpenShiftDeployment`.
Let's look at this deployment piece in detail. The new Tekton task makes use of Helm to define and deploy the Kubernetes resources to use. Your existing repository might not define Kubernetes resources at all (this is the default), or they might be expressed as OpenShift templates (in a folder named `openshift`) and applied with link:https://github.com/opendevstack/tailor[Tailor]. ODS pipeline only supports Helm at the moment, and requires the Kuberenetes resources (the Helm "chart") to be under version control as described below in the <<helm-chart,Helm Chart>> section.

After the `ods.yaml` and the Helm `chart` are added to the repository, the final step is to create a Bitbucket webhook pointing to the ODS pipeline installation. Disable the existing Jenkins webhook setting before creating a new one as described below in the <<webhook-configuration,Webhook Configuration>> section.

== Creating an `ods-pipeline`-enabled repository from scratch

In this scenario, we start from a blank repository. Like in the previous scenario, we will assume we want to build a Go application.

First, add an `ods.yaml` file to the root of the repository:

.ods.yaml
[source,yaml]
----
branchToEnvironmentMapping:
- branch: master
  environment: dev

environments:
- name: dev
  namespace: foo-dev
  stage: dev

pipeline:
  tasks:
  - name: backend-build-go
    taskRef:
      kind: ClusterTask
      name: ods-build-go-v0-1-1
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: backend-package-image
    taskRef:
      kind: ClusterTask
      name: ods-package-image-v0-1-1
    runAfter:
    - backend-build-go
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: backend-deploy
    taskRef:
      kind: ClusterTask
      name: ods-deploy-helm-v0-1-1
    runAfter:
    - backend-package-image
    workspaces:
    - name: source
      workspace: shared-workspace
----

The `ods-package-image-v0-1-1` task assumes the Docker context in `docker`, and the `Dockerfile` located inside that folder. Therefore, create a folder `docker` and create a `Dockerfile` inside like this one:

.Dockerfile
[source]
----
FROM alpine

COPY app app

EXPOSE 8080

CMD ["./app"]
----

The `ods-deploy-helm-v0-1-1` requires a Helm chart to be present to deploy the Kubernetes resources for the application. Add it as described below in the <<helm-chart,Helm Chart>> section.

Finally, setup a Bitbucket webhook pointing to the ODS pipeline installation as described below in the <<webhook-configuration,Webhook Configuration>> section.

[[helm-chart]]
== Helm Chart

ODS pipeline only supports deploying Kubernetes resources with Helm at the moment, and requires the Helm chart to be under version control. Please see the link:https://github.com/opendevstack/tailor/wiki/Migrating-from-Tailor-to-Helm#ods-quickstarter-migration[ODS Quickstarter Migration Guide] of Tailor for help how to create that chart.

[[webhook-configuration]]
== Webhook Configuration

To setup a webhook, go to "Repository Settings > Webhooks" and create a new webhook:

* "Name": choose any name you wish, e.g. `ods-pipeline`
* "URL": enter the URL of the route of your event listener
* "Secret": enter the value of the `secret` field in the OpenShift `ods-bitbucket-webhook` Secret.

Select the "Repository: Push" and "Pull request: Opened" events and save the configuration.

Once both `ods.yaml` and webhook configuration exist, any push in that repo will trigger the pipeline described in `ods.yaml`.

== Next Steps

Once you have done your first steps, consult the link:ods-configuration.adoc[`ods.yaml` reference] and the link:tasks/[tasks reference] for more information.

For an end-to-end example, have a look at the link:example-project.adoc[example project].
