# Working with secrets in Helm

The link:tasks/ods-deploy-helm.adoc[`ods-deploy-helm`] task supports encrypted secrets via the link:https://github.com/jkroepke/helm-secrets[`helm-secrets`] plugin. All Helm values which contain sensitive information such as passwords should be encrypted at rest. This guide will show how to do that.

## Overview

`helm-secrets` supports different ways to encrypt secrets at rest. The `ods-deploy-helm` task supports PGP key encryption. In a nutshell, the content is encrypted using a list of public keys. Owners of the corresponding private keys can decrypt the content. As such, you must encrypt the content against a public key and the corresponding private key must be made available to `ods-deploy-helm`.

## Local Setup

First you'll need a GPG keypair. If you are migrating from link:https://github.com/opendevstack/tailor[Tailor] you might already have a GPG keypair and you can simply continue to use that one. You may also use any other GPG keypair you already have.

If you do not have a GPG keypair yet or want to create a new one for this purpose, follow the link:https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key[Generating a new GPG key] instructions.

At the end of the generation, you see a 40 character fingerprint. Make a note of this as we'll need it in a second. If you already had a GPG key and you do not know its fingerprint, `gpg --list-keys` is your friend.

Once you have a GPG keypair and its fingerprint, create a `.sops.yaml` file in the `chart` directory:

..sops.yaml
[source,yaml]
----
creation_rules:
  - pgp: "<fingerprint here>"
----

`.sops.yaml` configures link:https://github.com/mozilla/sops[SOPS], which is a tool used by the `helm-secrets` plugin under the hood to encrypt and decrypt secrets.

Finally, if you did not install `helm` or the `helm-secrets` plugin locally yet, you will need those tools to edit the secrets. See link:https://helm.sh/docs/intro/install/[Installing Helm] and link:https://github.com/jkroepke/helm-secrets#installation-and-dependencies[helm-secrets installation and dependencies] to install the latest versions.

Now you are ready to work with secret files!

## Editing Secrets

The `helm-secrets` plugin offers a few commands to edit with secrets. See all of them via `helm secrets --help`.

To create a new secrets file or edit an existing one, use `helm secrets edit <filename>.yaml`. This will open an editor and let you enter and modify secrets in plain text, which will then get encrypted when you save.

It is common practice ot use `secrets.` as a prefix and `.yaml` as extension for your secret files. The `ods-deploy-helm` task will automatically pick up `secrets.yaml` and secret files corresponding to the target environment, see the link:tasks/ods-deploy-helm.adoc[`ods-deploy-helm`] task documentation.

## Using Secrets in Pipelines

Once you have encrypted secrets, the `ods-deploy-helm` task needs to decrypt them on the fly. In order to do this, it needs access to a private key which can decrypt the content. You can expose this to the task via a Kubernetes `Secret` resource. First, export the private key like this:

```
gpg --output sops.asc --armor --export-secret-key <the-email-address-you-used@example.com> | kubectl create secret generic helm-secrets-private-key \
  --namespace=<your cd namespace> \
  --from-file=sops.asc=/dev/stdin
```

This will create a `Secret` named `helm-secrets-private-key` in the namespace you specify. The private key is then the value of the field `sops.asc`. The secret will automatically be detected by the `ods-deploy-helm` task, and the private key will be imported into the GPG keyring so that the `helm-secrets` plugin can use it. Note that the field must be named `sops.asc`. If you wish to use a different secret name (e.g. to use different private keys for different repos in the same namespace), you may do so, by supplying a value for the `private-key-secret` parameter of the `ods-deploy-helm` task.

Note that if you used the link:user-installation.adoc[User Installation] instructions to setup the namespace in which your pipelines run, you have a Git repository which defines the infrastructure of this namespace. If you want to use that approach as well to define the `Secret` holding the private key, you can do so by adding a `secret.yaml` file to the chart and have Helm create it instead of using `kubectl create` as explained above. And because the user installation instructions use `git subtree` as a means to setup/update the Helm chart, any changes (such as a custom `secret.yaml` file) are preserved during updates of `ods-pipeline`.
