:toc:

= Working with secrets in Helm

The link:tasks/ods-deploy-helm.adoc[`ods-deploy-helm`] task supports encrypted secrets via the link:https://github.com/jkroepke/helm-secrets[`helm-secrets`] plugin, using link:https://github.com/mozilla/sops[`sops`] and link:https://github.com/FiloSottile/age[`age`] under the hood. All Helm values which contain sensitive information such as passwords should be encrypted at rest. This guide will show how to do that.

== Overview

`helm-secrets` supports different ways to encrypt secrets at rest. The `ods-deploy-helm` task supports age key encryption. In a nutshell, the content is encrypted using a list of age public keys. Owners of the corresponding age secret keys can decrypt the content. As such, you must encrypt the content against an age public key and the corresponding age secret key must be made available to `ods-deploy-helm`.

== Local Setup

To begin with, make sure you have link:https://helm.sh/docs/intro/install/[`helm`] (including the link:https://github.com/jkroepke/helm-secrets[`helm-secrets`] plugin), link:https://github.com/mozilla/sops[`sops`] and link:https://github.com/FiloSottile/age[`age`] installed.

Further, you'll need an age key to encrypt and/or decrypt secret files. If you do not have an age key yet or want to create a new one for this purpose, you can generate one via `age-keygen`. As described in the `sops` link:https://github.com/mozilla/sops#22encrypting-using-age[documentation], when decrypting using `age`, `sops` will look for a text file name `keys.txt` located in a `sops` subdirectory of your user configuration directory. Therefore it is best to place your age key in that directory. On Linux, this would be `$XDG_CONFIG_HOME/sops/age/keys.txt` (if `$XDG_CONFIG_HOME` is not set, it is usually `$HOME/.config`). On macOS, this would be `$HOME/Library/Application\ Support/sops/age/keys.txt`. On Windows, this would be `%AppData%\sops\age\keys.txt`.

WARNING: If you do not use your user configuration directory as the location of your age key, you need to specify its location via `SOPS_AGE_KEY_FILE`.

A key pair for encryption can be created by running:

[source]
----
mkdir -p <your_user_config_dir>/sops/age
age-keygen -o <your_user_config_dir>/sops/age/keys.txt
----

Now you are ready to work with secret files!

== Editing Secrets

In the age keys.txt file you see a commented line with `#public key: <public key value>`. Take this public key and use it to create an encrypted version of your not-yet encrypted `secrets.yaml`:

[source]
----
sops --encrypt --age <your_age_public_key> --in-place secrets.yaml
----

NOTE: you can add multiple recipients (e.g.: each team member has its own age key) comma-separated:

[source]
----
sops --encrypt --age <your_age_public_key>,<another_age_public_key> --in-place secrets.yaml
----

From now on, you can also edit the secrets through a simpler interface provided by the `helm-secrets` plugin:

[source]
----
helm secrets edit secrets.yaml
----

Next to the `edit` command, the `helm-secrets` plugin offers a few other commands to work with secrets. See all of them via `helm secrets --help`.

It is common practice ot use `secrets.` as a prefix and `.yaml` as extension for your secret files. The `ods-deploy-helm` task will automatically pick up `secrets.yaml` and secret files corresponding to the target environment, see the link:tasks/ods-deploy-helm.adoc[`ods-deploy-helm`] task documentation.

== Using Secrets in Pipelines

Once you have encrypted secrets, the `ods-deploy-helm` task needs to decrypt them on the fly. In order to do this, it needs access to an age key which can decrypt the content. You can expose this to the task via a Kubernetes `Secret` resource. You can create such a resource containing a new age key by running:

[source]
----
age-keygen | kubectl create secret generic helm-secrets-age-key \
  --namespace=<your cd namespace> \
  --from-file=key.txt=/dev/stdin
----

This will create a `Secret` named `helm-secrets-age-key` in the namespace you specify. The age key is then the value of the field `key.txt`. The secret will automatically be detected by the `ods-deploy-helm` task, and the age key will be loaded via `SOPS_AGE_KEY_FILE` so that the `helm-secrets` plugin can use it. Note that the field must be named `key.txt`. If you wish to use a different secret name (e.g. to use different private keys for different repos in the same namespace), you may do so, by supplying a value for the `age-key-secret` parameter of the `ods-deploy-helm` task.

NOTE: If you used the link:installation.adoc[Installation Guide] to setup the namespace in which your pipelines run, you have a Git repository which defines the infrastructure of this namespace. If you want to use that approach as well to define the `Secret` holding the age key, you can do so by adding a `secret.yaml` file to the chart and have Helm create it instead of using `kubectl create` as explained above. And because the link:installation.adoc[Installation Guide] uses `git subtree` as a means to setup/update the Helm chart, any changes (such as a custom `secret.yaml` file) are preserved during updates of `ods-pipeline`.

== Adding more recipients to encrypted files

If you want to give additional people access to view and edit secrets, you can do so via the following:

[source]
----
sops -r -i --add-age <another_age_public_key> secrets.yaml
----
More information can be found in link:https://github.com/mozilla/sops#adding-and-removing-keys[`sops documentation`]
