= Installation Guide
:toc:

This guide will show how to install `ods-pipeline` in an existing ODS project. It is possible to use the new Tekton pipelines approach and the classic Jenkins approach side by side.

Note that at the moment, `ods-pipeline` is somewhat compatible with an existing ODS 3.x/4.x installation, but it is not integrated (yet). If `ods-pipeline` gets integrated into OpenDevStack in the future, then the installation guide as presented below may not be needed anymore as the setup process might be automated then. However, the executed steps will likely be similar.

The guide will install the following required resources:

* Basic `BuildConfig`, `ImageStream` and `Task` resources
* `ConfigMap` and `Secret` resources, e.g. holding credentials of centrally installed tools such as Nexus and SonarQube
* ODS pipeline manager, which is managing and triggering pipelines in response to Bitbucket webhook requests

== Prerequisites

You'll need:

* A namespace in an OpenShift cluster (such as `foo-cd` from an existing ODS project) and a project in Bitbucket (such as `FOO`)
* `git`, `oc` and `helm` (with plugins link:https://github.com/databus23/helm-diff[`helm-diff`] and link:https://github.com/jkroepke/helm-secrets[`helm-secrets`]) installed locally
* to be logged into OpenShift on the command line

== Instructions

First, create a repository in Bitbucket, e.g. `foo-cd`. The name can be anything, but since the repository will define the resources in namespace `foo-cd` in code, it makes sense to mirror the namespace name. Clone the repository locally and make an initial commit, e.g. by adding a readme file.

IMPORTANT: The following commands will fail in an empty Git repository, so make sure you have made at least one commit in the repository.

Then, use `git subtree` to get the required sources. The following commands may look a bit complicated, but in a nutshell, they are simply adding one folder (`deploy/`) from the `opendestack/ods-pipeline` repository at the given revision (e.g. `master`) into your new local repository at the path `deploy`.

[source]
----
pipelineGitRef=v0.5.0 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --prefix=deploy -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree add --squash --prefix=deploy subtree-split-branch-$pipelineGitRef
----

Once this is done, change to the new folder `deploy` to configure the values and secrets to use for the installation.

For the values, just run:

[source]
----
cp ods-pipeline/values.yaml values.yaml
----

Regarding the secrets, it is recommended to encrypt them at rest, therefore the following describes how to first encrypt them, but also how to edit them using the `helm-secrets` plugin.

For this, you'll need to install `link:https://github.com/mozilla/sops[sops]` and `link:https://github.com/FiloSottile/age[age]` for en-/decryption of the `secrets.yaml` file.

As described in the `sops` link:https://github.com/mozilla/sops#22encrypting-using-age[documentation], when decrypting
using `age`, `sops` will look for a text file name `keys.txt` located in a `sops` subdirectory of your user
configuration directory. On Linux, this would be `$XDG_CONFIG_HOME/sops/age/keys.txt` (if `$XDG_CONFIG_HOME` is not set,
it is usually `$HOME/.config`). On macOS, this would be `$HOME/Library/Application\ Support/sops/age/keys.txt`. On Windows,
this would be `%AppData%\sops\age\keys.txt`. You can specify the location of this file manually by setting the
environment variable `SOPS_AGE_KEY_FILE`. The following will refer to this user configuration directory as `<your_user_config_dir>`.

Knowing this, a key pair for encryption can be created by running:

[source]
----
mkdir -p <your_user_config_dir>/sops/age
age-keygen -o <your_user_config_dir>/sops/age/keys.txt
----

This prints as a result the public key (alternatively you can find it in the `keys.txt`) which looks similar to this:

[source]
----
Public key: age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
----

The following will refer to this public key as `<your_age_public_key>`.
Take the public key and use it to create an encrypted version of your `secrets.yaml`:

[source]
----
sops --encrypt --age <your_age_public_key> ods-pipeline/secrets.yaml > secrets.yaml
----

NOTE: you can add multiple recipients (e.g.: each team member has its own age key) comma-separated:

[source]
----
sops --encrypt --age <your_age_public_key>,<another_age_public_key> ods-pipeline/secrets.yaml > secrets.yaml
----

Now you can edit the secrets with:

[source]
----
helm secrets edit secrets.yaml
----

CAUTION: If you configure an Aqua scanner download URL, make sure that username/password are URL-encoded and that the `scannercli` version matches your Aqua server version.

IMPORTANT: In ODS 4.0.0, the central Nexus instance does not have the repositories `ods-temporary-artifacts` and `ods-permanent-artifacts` after the default ODS installation. If those repositories are not present in your Nexus instance yet, you will need to create them manually. The repositories are of type "raw" and should not allow re-deployment of artifacts. It is recommended to use blob stores for both. As administrator, you may prune the `ods-temporary-artifacts` repository using cleanup policies of your own choosing. The `ods-permanent-artifacts` repository should not be cleaned up or have a retention period matching your organisation policy of record retention.

Now fill in the variables as described in the comments in both (values.yaml and secrets.yaml) files. Then you can install the resources via `./install.sh -n <your_cd_namespace> -f values.yaml,secrets.yaml` (make sure to replace the namespace). You may also use `--dry-run` to see the changes first.

NOTE: After successful installation in OpenShift, builds for the container images used in the pipeline manager and Tekton tasks will be triggered automatically. It is recommended to check that all builds succeed before proceeding.

Finally, run `oc -n <your_cd_namespace> expose svc ods-pipeline` to expose the service listener. Make a note of the exposed URL as you'll need it to create webhooks in Bitbucket (together with the webhook secret that is stored in the `Secret/ods-bitbucket-webhook` resource).

IMPORTANT: The `pipeline` serviceaccount needs at least `edit` or even `admin` permissions in the Kubernetes namespaces it deploys to (e.g. `foo-dev` and `foo-test`).

Now you are ready to link:convert-quickstarter-component.adoc[use ODS pipeline for your repositories]!

== Updating

You may fetch updates (e.g. new versions) of `ods-pipeline` like this:

[source]
----
pipelineGitRef=v0.5.0 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --prefix=deploy -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree merge --prefix=deploy subtree-split-branch-$pipelineGitRef --squash
----

Now, compare if any new values have been introduced and update the values and secrets file accordingly.

Afterwards you can update the resources via `./install.sh -n <your_cd_namespace> -f values.yaml,secrets.yaml`. You may also use `--dry-run` to see the changes first.

NOTE: After successful installation in OpenShift, builds for the container images used in the pipeline manager and Tekton tasks will be triggered automatically. It is recommended to check that all builds succeed before proceeding.

Once the resources in your namespace are updated, you can update the `ods.yaml` files in your repository and point to the new tasks, e.g. changing `ods-build-go-v0-4-0` to `ods-build-go-v0-5-0`.
