= Installation Guide
:toc:

This guide will show how to install ODS Pipeline in an existing ODS project. It is possible to use ODS Pipeline and the classic Jenkins CI/CD setup side by side.

An ODS Pipeline installation consists of the following resources:

* A pipeline manager, which is creating pipeline runs in response to Bitbucket webhook requests
* A start and finish task which will get injected into every pipeline run
* `ConfigMap` and `Secret` resources, e.g. holding credentials of centrally installed tools such as Nexus and Bitbucket


== Prerequisites

You'll need:

* A namespace in an OpenShift/Kubernetes cluster (such as `foo-cd` from an existing ODS project) and a project in Bitbucket (such as `FOO`).
* `git`, link:https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html[`oc`] (or link:https://kubernetes.io/docs/reference/kubectl/[`kubectl`]) and link:https://helm.sh[`helm`] installed locally. The plugin link:https://github.com/databus23/helm-diff[`helm-diff`] is optional but recommended.

== Installation Instructions

ODS Pipeline is packaged as a Helm chart. The installation procedure consists of three quick steps:

1. Configuring the chart values
2. Running the install script (which will deploy the Helm chart)
3. Exposing a route to the pipeline manager

=== Step 1: Configuring the chart values

Download the template and fill in the values according to the comments in that file.

[source]
----
curl -L https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/deploy/values.yaml.tmpl -o values.yaml
----

TIP: It is recommended to keep this file around after the installation so that it can be reused when updating ODS Pipeline to future versions.

=== Step 2: Running the install script

==== Option 1: With external API access

If you have access to the OpenShift API from your local machine, simply login to the OpenShift cluster and install ODS Pipeline by running:

[source]
----
./install.sh -n <your_cd_namespace>
----

The script will interactively ask for credentials (such as Bitbucket access token) and will create corresponding K8s secrets. If you prefer to pass these secrets via flags, see `./install.sh --help` for all options.

IMPORTANT: If tasks need to trust a private certificate, pass `--private-cert <host>`. This will create a K8s secret containing the certificate from the specified host, which will then be mounted in pods during task runs.

TIP: You may pass `--dry-run` to review what `install.sh` will do before actually running the script.

==== Option 2: Without external API access

If you do not have access to the OpenShift API from your local machine, you can use the https://docs.openshift.com/container-platform/latest/web_console/odc-about-web-terminal.html[OpenShift Web Terminal] to install ODS Pipeline. Open a web terminal in your `*-cd` namespace, then run:

[source]
----
curl -L https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/scripts/web-terminal-install.sh | bash
----

This will install all prerequisites automatically. Then you can clone the repository and run `./install.sh -n <your_cd_namespace>`.

`./install.sh` will interactively ask for credentials (such as Bitbucket access token) and will create corresponding K8s secrets. If you prefer to pass these secrets via flags, see `./install.sh --help` for all options.

=== Step 3: Exposing a route to the pipeline manager

Create an HTTPS route to expose the `ods-pipeline` service. You'll need the exposed URL (together with the webhook secret that is stored in the `ods-bitbucket-webhook` K8s secret) when you create webhooks in Bitbucket repositories later.

Done, now you are ready to link:add-to-repository.adoc[enable your repositories to use ODS pipeline]!

IMPORTANT: The `pipeline` serviceaccount needs `admin` permissions in the Kubernetes namespaces it deploys to (e.g. `foo-dev` and `foo-test`). You must create rolebindings for this manually.

CAUTION: An important feature of ODS Pipeline is to retain pipeline run artifacts in Nexus and re-use them future pipeline runs (e.g. to promote built container images to another environment). For this purpose, you should create a few `raw` repositories in Nexus. These repositories should not allow re-deployment of artifacts. For example, you might want to have `ods-pipeline-dev`, `ods-pipeline-qa` and `ods-pipeline-prod` repositories, each with a different cleanup policy as fitting your needs. You can then use these repositories from your pipeline to store artifacts and enforce a progression of artifacts from DEV > QA > PROD.


== Update Instructions

The update procedure consists of two quick steps:

1. Updating the chart values if required
2. Running the install script (which will deploy the Helm chart)

=== Step 1: Updating the chart values

Check if any new values have been introduced in `values.yaml.tmpl` and update your `values.yaml` (which you hopefully retained from the installation) accordingly.

=== Step 2: Running the install script

==== Option 1: With external API access

If you have access to the OpenShift API from your local machine, you can simply login to the OpenShift cluster in your terminal, then update the ODS Pipeline installation by running:

[source]
----
./install.sh -n <your_cd_namespace>
----

TIP: You may also use `--dry-run` to see the changes first.

TIP: By default, the credentials stored in the K8s secrets will not be updated. If you want to make a change, pass any new values as flags to `install.sh` (see `./install.sh --help` for all options) or update the secrets manually.

==== Option 2: Without external API access

If you do not have access to the OpenShift API from your local machine, you can use the https://docs.openshift.com/container-platform/latest/web_console/odc-about-web-terminal.html[OpenShift Web Terminal] to install ODS Pipeline. Open a web terminal in your `*-cd` namespace, then run:

[source]
----
curl -L https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/scripts/web-terminal-install.sh | bash
----

This will install all prerequisites automatically and update your ODS Pipeline installation to the latest state of your Git repository.

TIP: The credentials stored in the K8s secrets will not be updated. If you need to change those, update them manually.
