= Installation Guide
:toc:

This guide will show how to install ODS Pipeline in an existing ODS project. It is possible to use ODS Pipeline and the classic Jenkins CI/CD setup side by side.

An ODS Pipeline installation consists of the following resources:

* `BuildConfig`, `ImageStream` and `Task` resources
* `ConfigMap` and `Secret` resources, e.g. holding credentials of centrally installed tools such as Nexus and SonarQube
* A pipeline manager, which is creating pipeline runs in response to Bitbucket webhook requests

== Prerequisites

You'll need:

* A namespace in an OpenShift cluster (such as `foo-cd` from an existing ODS project) and a project in Bitbucket (such as `FOO`).
* `git`, link:https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html[`oc`] (or link:https://kubernetes.io/docs/reference/kubectl/[`kubectl`]) and link:https://helm.sh[`helm`] installed locally. The plugin link:https://github.com/databus23/helm-diff[`helm-diff`] is optional but recommended.

== Installation Instructions

The installation procedure consists of two steps:

1. Creating a Git repository defining the configuration of the ODS Pipeline installation
2. Using Helm to install from this Git repository

===  Creating a Git repository

Create a new repository in Bitbucket, e.g. `foo-cd`. The name can be anything, but since the repository will define the K8s resources of namespace `foo-cd` in code, it makes sense to mirror the namespace name. Clone the repository locally and make an initial commit, e.g. by adding a readme file.

IMPORTANT: The following commands will fail in an empty Git repository, so make sure you have made at least one commit in this repository.

Now use `git subtree` to get the required source files. The following commands may look a bit complicated, but in a nutshell, they are simply adding one folder (`deploy/`) from the `opendevstack/ods-pipeline` repository at the given revision (e.g. `master`) into your new local repository at the path `deploy`. The benefit of this approach is that it'll make updating ODS Pipeline simple.

[source]
----
pipelineGitRef=v0.8.0 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --prefix=deploy -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree add --squash --prefix=deploy subtree-split-branch-$pipelineGitRef
----

Once this is done, change to the new folder `deploy` to configure the values of the Helm Chart. Run `cp values.yaml.tmpl values.yaml`, then edit `values.yaml` as described in the comments in that file. Commit and push before proceeding to the next step.

=== Using Helm to install from the Git repository

==== Option 1: With external API access

If you have access to the OpenShift API from your local machine, you can simply login to the OpenShift cluster, then install ODS Pipeline by running:

[source]
----
./install.sh -n <your_cd_namespace>
----

The script will interactively ask for credentials (such as Bitbucket access token) and will create corresponding K8s secrets. If you prefer to pass these secrets via flags, see `./install.sh --help` for all options.

TIP: You may pass `--dry-run` to review what `install.sh` will do before actually running the script.

After you ran the install script, continue with the <<finishing-the-installation,Finishing the installation>> section.

==== Option 2: Without external API access

If you do not have access to the OpenShift API from your local machine, you can use the https://docs.openshift.com/container-platform/latest/web_console/odc-about-web-terminal.html[OpenShift Web Terminal] to install ODS Pipeline. Open a web terminal in your `*-cd` namespace, then run:

[source]
----
curl -L https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/scripts/web-terminal-install.sh | bash
----

This will install all prerequisites automatically. Then you can clone the repository and run `./install.sh -n <your_cd_namespace>` in the terminal.

`./install.sh` will interactively ask for credentials (such as Bitbucket access token) and will create corresponding K8s secrets. If you prefer to pass these secrets via flags, see `./install.sh --help` for all options.

After you ran the install script, continue with the <<finishing-the-installation,Finishing the installation>> section.

==== Finishing the installation

After successful installation in OpenShift, builds for the container images used in the pipeline manager and Tekton tasks will be triggered automatically. It is recommended to check that all builds succeed before proceeding.

Finally, create an HTTPS route to expose the `ods-pipeline` service. You'll need the exposed URL (together with the webhook secret that is stored in the `ods-bitbucket-webhook` K8s secret) when you create webhooks in Bitbucket repositories later.

IMPORTANT: The `pipeline` serviceaccount needs `admin` permissions in the Kubernetes namespaces it deploys to (e.g. `foo-dev` and `foo-test`). You must create rolebindings for this manually.

CAUTION: The default installation of ODS 4.x does not create `ods-temporary-artifacts` and `ods-permanent-artifacts` repositories in Nexus, however they are required for ODS Pipeline to work. The repositories need to be of type `raw` and should not allow re-deployment of artifacts. It is recommended to use separate blob stores for both. As administrator, you may prune the `ods-temporary-artifacts` repository using cleanup policies of your own choosing. The `ods-permanent-artifacts` repository should not be cleaned up or have a retention period matching your organisation policy of record retention.

Now you are ready to link:add-to-repository.adoc[enable your repositories to use ODS pipeline]!

== Update Instructions

The update procedure consists of two steps:

1. Updating the Git repository defining the configuration of the ODS Pipeline installation
2. Using Helm to install from the Git repository

=== Updating the Git repository

You may fetch updates (e.g. new versions) of `ods-pipeline` like this:

[source]
----
pipelineGitRef=v0.8.0 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --prefix=deploy -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree merge --prefix=deploy subtree-split-branch-$pipelineGitRef --squash
----

Afterwards, check if any new values have been introduced in `values.yaml.tmpl` and update `values.yaml` accordingly. Commit and push the result.

=== Using Helm to install from the Git repository

==== Option 1: With external API access

If you have access to the OpenShift API from your local machine, you can simply login to the OpenShift cluster in your terminal, then update the ODS Pipeline installation by running:

[source]
----
./install.sh -n <your_cd_namespace>
----

TIP: You may also use `--dry-run` to see the changes first.

After you ran the script, continue with the <<finishing-the-update,Finishing the update>> section.

TIP: By default, the credentials stored in the K8s secrets will not be updated. If you want to make a change, pass any new values as flags to `install.sh` (see `./install.sh --help` for all options) or update the secrets manually.

==== Option 2: Without external API access

If you do not have access to the OpenShift API from your local machine, you can use the https://docs.openshift.com/container-platform/latest/web_console/odc-about-web-terminal.html[OpenShift Web Terminal] to install ODS Pipeline. Open a web terminal in your `*-cd` namespace, then run:

[source]
----
curl -L https://raw.githubusercontent.com/opendevstack/ods-pipeline/master/scripts/web-terminal-install.sh | bash
----

This will install all prerequisites automatically and update your ODS Pipeline installation to the latest state of your Git repository.

TIP: The credentials stored in the K8s secrets will not be updated. If you need to change those, update them manually.

==== Finishing the update

After successful installation in OpenShift, builds for the container images used in the pipeline manager and Tekton tasks will be triggered automatically. It is recommended to check that all builds succeed before proceeding.

Once the resources in your namespace are updated, you likely have to update the `ods.yaml` files in your repository to point to the new tasks, e.g. changing `ods-build-go-v0-6-0` to `ods-build-go-v0-8-0`. Whether or not you have to update the `ods.yaml` file depends whether the task suffix (controlled by the value `taskSuffix`) has changed due to the update.
