:toc:

= `ODS.YAML` Reference

This guide will explain how to configure pipelines for your repositories in an `ods.yaml` file. The configuration in `ods.yaml` allows the following top-level fields:

* `pipelines`
* `repositories`
* `version`

== `pipelines`

The `pipelines` field allows to define multiple pipelines. Each pipeline specifies when it is triggered (e.g. when a Git push occurs in a specific branch), and which tasks (e.g. build, package, deploy) to run. Example:

.ods.yaml
[source,yaml]
----
pipelines:
- triggers:
  - branches: ["main"]
  tasks:
  - name: build
    taskRef:
      kind: Task
      name: ods-build-go-v0-11-1
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: package
    taskRef:
      kind: Task
      name: ods-package-image-v0-11-1
    runAfter:
    - build
    workspaces:
    - name: source
      workspace: shared-workspace
----

The pipelines created based on the configuration will have a workspace named `shared-workspace` available, which is backed by a PVC (named `ods-pipeline-<component>`) in your namespace.

=== Configuring pipeline tasks

Normal tasks may be specified under `tasks`. Each task is a plain Tekton definition. See the Tekton documentation on link:https://tekton.dev/vault/pipelines-v0.41.x-lts/pipelines/#adding-tasks-to-the-pipeline[Adding Tasks to the Pipeline] for more information.

The exact name of the task (`taskRef.name` field) depends on the version of `ods-pipeline` that is installed in your project. Available tasks for you to use can be found in your OpenShift console UI under "Pipelines > Tasks".

Next to the tasks you specify, `ods-pipeline` will automatically inject two tasks into the pipeline, `ods-start` and `ods-finish`:

* `ods-start` is inserted as the very first task, checking out the repository given in the webhook, setting the Bitbucket build status and dealing with Nexus artifacts, etc.
* `ods-finish` task is added as a final task to the pipeline. Final tasks run at the end, regardless whether all previous tasks succeeded. The `ods-finish` sets the Bitbucket build status and deals with Nexus artifacts, etc.

Alternatively to referencing tasks, inline task definitions can also be specified:

.ods.yaml
[source,yaml]
----
pipelines:
- tasks:
  - name: build
    taskSpec:
      steps:
      - name: message
        image: ubuntu
        script: |
          #!/usr/bin/env bash
          echo "hello world"
          cat README.md # assuming there is a README.md file at the root of the repo
        workingDir: $(workspaces.source.path)    
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: shared-workspace
----

Further, if link:https://tekton.dev/vault/pipelines-v0.43.x/install/#configuring-built-in-remote-task-and-pipeline-resolution[remote resolution is enabled], tasks can also be resolved remotely, e.g. link:https://tekton.dev/vault/pipelines-v0.41.x-lts/git-resolver/#task-resolution[from Git]:

.ods.yaml
[source,yaml]
----
pipelines:
- tasks:
  - name: build
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/opendevstack/ods-pipeline.git
      - name: revision
        value: v0.11.1
      - name: pathInRepo
        value: tasks/ods-build-go.yaml
      workspaces:
      - name: source
        workspace: shared-workspace
----

=== Configuring final tasks

You can also specify further final tasks to be added to the pipeline by specifying them under `finally`. Example:

.ods.yaml
[source,yaml]
----
pipelines:
- tasks: [ ... ]
  finally:
  - name: foo
    taskRef:
      kind: Task
      name: foo
    workspaces:
    - name: source
      workspace: shared-workspace
----

Note that you cannot configure the execution order of final tasks. Final tasks all run simultaneously. For more information on final tasks, see the Tekton documentation on link:https://tekton.dev/vault/pipelines-v0.41.x-lts/pipelines/#adding-finally-to-the-pipeline[Adding Finally to the Pipeline].

=== Configuring pipeline triggers

Using the `triggers` section, it is possible to narrow down in response to which events the pipeline should run. Further, each trigger can pass individual parameters to the referenced pipeline, allowing to modify the behaviour of the pipeline.

==== Matching webhook events

Example:
```
pipelines:
- triggers:
  - events: ["repo:refs_changed", "pr:*"]
    branches: ["feature/*"]
    exceptBranches: ["feature/foo"]
    prComment: "/build"
  tasks: []
```

The following selection criteria may be specified:

`events`:: List of events that trigger the pipeline. Patterns as supported by link:https://pkg.go.dev/path#Match[`path.Match`] may be used to match events. In case the `event` property is omitted in `ods.yaml`, any supported event will trigger the respective pipeline.
`branches`:: List of branches to which the triggering event shall refer. Patterns as supported by link:https://pkg.go.dev/path#Match[`path.Match`] may be used to match branches. Not specifying the `branches` criterion will match webhook events on any branch in the repository.
`exceptBranches`:: List of branches to which the triggering event may not refer. Patterns as supported by link:https://pkg.go.dev/path#Match[`path.Match`] may be used to match the excluded branches. Omitting the criterion will lead to none of the branches referred to in the webhook event to be excluded.
`prComment`:: Define a prefix a comment has to start with. Might be used to implement functionality like slash commands. If omitted, comments won't be considered in the pipeline selection process.

Currently, the Bitbucket events `repo:refs_changed` (fired on push to a Bitbucket repository) and any Pull Request related events (event types with prefix `pr:`) are supported (for a full list of events, please refer to the link:https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html[Atlassian Bitbucket Documentation]). Only the first trigger matching all conditions will be selected. If no trigger section is specified, the pipeline will always match.

==== Passing parameters

The `params` field of each trigger can be used to pass parameters to the pipeline and its tasks. This mechanism can be used to pass dynamic parameter values based on the Git ref, for example to deploy into different namespaces depending on the checked out branch.

Example:

.ods.yaml
[source,yaml]
----
pipelines:
- triggers:
  - branches: ["develop"]
    params:
    - name: deploy.namespace
      value: foo-dev
  - branches: ["production"]
    params:
    - name: deploy.namespace
      value: foo-prod
  tasks:
  - name: deploy
    taskRef:
      kind: Task
      name: ods-deploy-helm-v0-11-1
    workspaces:
    - name: source
      workspace: shared-workspace
----

Parameters when prefixed with `<task-name>.` are passed to the task named `<task-name>`. When no prefix is set, the parameter is available as a normal pipeline run parameter.

=== Configuring other pipeline run aspects

Aside from `tasks` and `finally`, you may also specify https://tekton.dev/vault/pipelines-v0.41.x-lts/pipelineruns/#configuring-a-failure-timeout[`timeouts`], link:https://tekton.dev/vault/pipelines-v0.41.x-lts/pipelineruns/#specifying-a-pod-template[`podTemplate`] and link:https://tekton.dev/vault/pipelines-v0.41.x-lts/pipelineruns/#specifying-taskrunspecs[`taskRunSpecs`] for more advanced configuration.

For example, the compute resources of a remotely resolved task could be overriden like this (provided `enable-api-fields` is set to `alpha`):

.ods.yaml
[source,yaml]
----
pipelines:
- tasks:
  - name: build
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/opendevstack/ods-pipeline.git
      - name: revision
        value: v0.11.1
      - name: pathInRepo
        value: tasks/ods-build-go.yaml
      workspaces:
      - name: source
        workspace: shared-workspace
  taskRunSpecs:
  - pipelineTaskName: build
    stepOverrides:
    - name: build-go-binary
      resources:
        requests:
          memory: 2Gi
----

== `version`

`version` is an optional field that can specify a link:https://semver.org[SemVer] version. Its value will be available in the pipeline context.

== `repositories`

If your application is made out of multiple components, you may want to have one "umbrella" repository that ties all those components together and deploys the whole application together. In this case, the umbrella repository can specify the subrepositories via the `repositories` field. Example:

.ods.yaml
[source,yaml]
----
repositories:
- name: foo
- name: bar
  branch: main
  url: https://bitbucket.acme.org/scm/baz/bar.git
----

If the repository does not specify a URL, the repository is assumed to be under the same organisation as the repository hosting the `ods.yaml` file. If no branch is given, `master` is used as a default.

Repositories listed in `ods.yaml` are checked out in `ods-start` in `.ods/repos` and any tasks in the pipeline can alter their behaviour based on the presence of subrepos. For example, the `ods-deploy-helm` task will package any charts in subrepos and add them to the chart in the umbrella repository, deploying all charts as one release.
