:toc:

= `ODS.YAML` Reference

This guide will explain how to configure pipelines for your repositories in an `ods.yaml` file. The configuration in `ods.yaml` allows five top-level fields:

* `pipeline`
* `environments`
* `branchToEnvironmentMapping`
* `version`
* `repositories`

== `pipeline`

The pipeline field allows to define the pipelines' tasks. Normal tasks may be specified under `tasks`. Example:

.ods.yaml
[source,yaml]
----
pipeline:
  - trigger:
      event: ["repo:refs_changed", "pr:*"]
      branches: ["feature/*"]
      exceptBranches: ["feature/foo"]
      prComment: "/build"
    tasks:
    - name: build
      taskRef:
        kind: Task
        name: ods-build-go-v0-10-1
      workspaces:
      - name: source
        workspace: shared-workspace
    - name: package
      taskRef:
        kind: Task
        name: ods-package-image-v0-10-1
      runAfter:
      - build
      workspaces:
      - name: source
        workspace: shared-workspace
----

Each task reference is just the plain Tekton definition. See the Tekton documentation on link:https://tekton.dev/vault/pipelines-v0.24.3/pipelines/#adding-tasks-to-the-pipeline[Adding Tasks to the Pipeline] for more information.

A typical `ods-pipeline` installation offers its task as `Task` resources, therefore the `taskRef.kind` needs to be `Task`. The value of the `taskRef.name` field depends on the version of `ods-pipeline` that is installed in your project. Available tasks for you to use can be found in your OpenShift console UI under "Pipelines > Tasks".

Alternatively to referencing tasks, ad-hoc task definitions can also be specified directly inside `ods.yaml`:

.ods.yaml
[source,yaml]
----
pipeline:
  - tasks:
    - name: build
      taskSpec:
        steps:
          - name: message
            image: ubuntu
            script: |
              #!/usr/bin/env bash
              echo "hello world"
              cat README.md # assuming there is a README.md file at the root of the repo
            workingDir: $(workspaces.source.path)    
        workspaces:
          - name: source
      workspaces:
      - name: source
        workspace: shared-workspace
----

The pipelines created based on the configuration will have a workspace named `shared-workspace` available, which is backed by a PVC (named `ods-pipeline`) in your namespace.

Next to the tasks you specify, `ods-pipeline` will automatically inject two tasks into the pipeline, `ods-start` and `ods-finish`. `ods-start` is inserted as the very first task, checking out the repository given in the webhook, setting the Bitbucket build status and dealing with Nexus artifacts, etc.

The `ods-finish` task is added as a final task to the pipeline. Final tasks run at the end, regardless whether all previous tasks succeeded. The `ods-finish` sets the Bitbucket build status and deals with Nexus artifacts, etc.

Using the `trigger` section, multiple pipelines can be configured, and the web hook data is matched against the conditions specified in the `trigger` section, selecting the pipeline to run. The following selection criteria may be specified:

`event`:: List of events that trigger the pipeline. Patterns as supported by link:https://pkg.go.dev/path#Match[`path.Match`] may be used to match events. In case the `event` property is omitted in `ods.yaml`, any supported event will trigger the respective pipeline.
`branches`:: List of branches to which the triggering event shall refer. Patterns as supported by link:https://pkg.go.dev/path#Match[`path.Match`] may be used to match branches. Not specifying the `branches` criterion will match webhook events on any branch in the repository.
`exceptBranches`:: List of branches to which the triggering event may not refer. Patterns as supported by link:https://pkg.go.dev/path#Match[`path.Match`] may be used to match the excluded branches. Omitting the criterion will lead to none of the branches referred to in the webhook event to be excluded.
`prComment`:: Define a prefix a comment has to start with. Might be used to implement functionality like slash commands. If omitted, comments won't be considered in the pipeline selection process.

Currently, the Bitbucket events `repo:refs_changed` (fired on push to a Bitbucket repository) and any Pull Request related events (event types with prefix `pr:`) are supported (for a full list of events, please refer to the link:https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html[Atlassian Bitbucket Documentation]). Only the first pipeline matching all conditions in the trigger section will be executed. If no trigger section is specified, the pipeline will always match.

You can also specify further final tasks to be added to the pipeline by specifying them under `finally`. Example:

.ods.yaml
[source,yaml]
----
pipeline:
  - tasks: [ ... ]
    finally:
    - name: foo
      taskRef:
        kind: Task
        name: foo
      workspaces:
      - name: source
        workspace: shared-workspace
----

Note that you cannot configure the execution order of final tasks. Final tasks all run simultaneously. For more information on final tasks, see the Tekton documentation on link:https://tekton.dev/vault/pipelines-v0.24.3/pipelines/#adding-finally-to-the-pipeline[Adding Finally to the Pipeline].

Aside from `tasks` and `finally`, you may also specify link:https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout[`timeouts`], link:https://tekton.dev/vault/pipelines-v0.24.3/pipelineruns/#specifying-a-pod-template[`podTemplate`] and link:https://tekton.dev/docs/pipelines/pipelineruns/#specifying-taskrunspecs[`taskRunSpecs`] for more advanced configuration (like overriding compute resources).



== `environments`

The `environments` field allows you to specify target environments to deploy to. Each environment must have a `name` and a `stage` field. Example:

.ods.yaml
[source,yaml]
----
environments:
- name: development
  stage: dev
----

The value of `name` may freely be chosen, but must begin and end with a lowercase `a-z` and can use `a-z0-9` and (`-`) in between. The `stage` must be one of `dev`, `qa` or `prod`. Each environment corresponds to one namespace in an OpenShift/Kubernetes cluster. The namespace may either be specified explicitly (via `namespace`), or it will be computed based on the project and the environment name (`<PROJECT>-<ENV-NAME>`). In the example above, `namespace` is not configured, therefore the target namespace will be resolved to `foo-development` (if the project is named `foo`). If `namespace` is specified it must follow the same rules as the `name` described above.

Environments may also be located external to the cluster in which the pipeline runs. In this case, an environment may specify further fields:

* `apiServer`: API server of the target cluster, including scheme
* `apiCredentialsSecret`: Name of the Secret resource holding the API user credentials in field `token`
* `registryHost`: Hostname of the target registry
* `config`: Additional configuration of the target in the form of a map. This information may be used by custom tasks.

== `branchToEnvironmentMapping`

In order for the pipeline to select an environment to deploy to, you have to configure which branch should be deployed to which environment. This can be done via `branchToEnvironmentMapping`. Example:

.ods.yaml
[source,yaml]
----
branchToEnvironmentMapping:
- branch: master
  environment: development
----

In this case, the `master` branch will be deployed to the environment with the name `development`.

The `branch` field also supports wildcard suffix match: use `&#42;` to match any branch, or e.g. `release/*` to match all branches that are prefixed with `release/`.

TIP: If you want to promote images between environments without rebuilding them, ensure that you are merging without merge commits (fast-forward, `--ff-only`).

== `version`

`version` is an optional field that can specify a link:https://semver.org[SemVer] version. Its value will be available in the pipeline context. The link:tasks/ods-start.adoc[`ods-start` task] requires a value to be present when the target environment is of stage `qa` or `prod`. When this is the case, the task applies Git tags (`v<VERSION>-rc.<NUMBER>` for `qa` and `v<VERSION>` for `prod`) to the repository and ensures that a pipeline run for a `qa` environment exist before allowing to proceed to a `prod` environment.

== `repositories`

If your application is made out of multiple components, you may want to have one "umbrella" repository that ties all those components together and deploys the whole application together. In this case, the umbrella repository can specify the subrepositories via the `repositories` field. Example:

.ods.yaml
[source,yaml]
----
repositories:
- name: foo
- name: bar
  branch: main
  url: https://bitbucket.acme.org/scm/baz/bar.git
----

If the repository does not specify a URL, the repository is assumed to be under the same organisation as the repository hosting the `ods.yaml` file. If no branch is given, `master` is used as a default.

Repositories listed in `ods.yaml` are checked out in `ods-start` in `.ods/repos` and any tasks in the pipeline can alter their behaviour based on the presence of subrepos. For example, the `ods-deploy-helm` task will package any charts in subrepos and add them to the chart in the umbrella repository, deploying all charts as one release.
