= Software Requirements

== General Requirements

=== Webhook Interceptor

[cols="1,3"]
|===
| REQ-INTERCEPTOR-1
a| The interceptor shall be able to respond to `repo:refs_changed` and `pr:opened` events.

* All other events shall be dropped.

| REQ-INTERCEPTOR-2
a| The interceptor shall not trigger pipelines for Git commits which message instructs to skip CI. Instructions may be anywhere in the commit message and may be one of:

* `[ci skip]`
* `[skip ci]`
* `***NO_CI***`

| REQ-INTERCEPTOR-3
a| The interceptor shall create or update a pipeline corresponding to the Git branch received in the webhook request.

* The pipeline name shall be made out of the component and the sanitized branch. A maximum of 63 characters shall be respected.
* The tasks (including `finally` tasks) of the pipline shall be read from the ODS config file in the repository.
|===

== Task Requirements

=== `ods-start`

[cols="1,3"]
|===
| REQ-TASK-START-1
a| The task shall check out the repository of given URL and Git ref into the mounted workspace, cleaning any previous contents. If the checked out `ods.y(a)ml` configures any child repositories, those shall be checked out as well from the configured URL and Git ref.

* All checkouts shall support shallow mode
* All checkouts shall support submodules

| REQ-TASK-START-2
a| The task shall store context information under `.ods` for each checked out repository:

* repository related information: project key, component key, repository name, Git URL, Git (full) ref, Git commit SHA, pull request base and pull request key.
* OpenShift related information: namespace
* deployment related information: version and environment

| REQ-TASK-START-3
| The task shall download all artifacts from Nexus belonging to the same commit being built and place them into the respective `.ods/artifacts` for each checked out repository.

| REQ-TASK-START-4
| The task shall set the Bitbucket build status of the commit being built to "in progress". The build status shall link back to the pipeline run.

| REQ-TASK-START-5
| The task shall fail when any child repository is missing a successful pipeline run artifact for the checked out commit.
|===

=== `ods-finish`

[cols="1,3"]
|===
| REQ-TASK-FINISH-1
| The task shall set the Bitbucket build status to "failed" or "successful", depending on whether all tasks succeeded or not. The build status shall link back to the pipeline run.

| REQ-TASK-FINISH-2
| The task shall create an artifact for the pipeline run, containing its name and status, provided that all tasks succeeded.

| REQ-TASK-FINISH-3
| The task shall upload all files in any `.ods/artifacts` folder to Nexus, storing them in a group named `/<PROJECT>/<REPOSITORY>/<GIT-COMMIT-SHA>`, provided that all tasks succeeded.
|===

=== `ods-build-go`

[cols="1,3"]
|===
| REQ-TASK-BUILD-GO-1
| The task shall check that all Go files are gofmt'd and fail if this is not the case.

| REQ-TASK-BUILD-GO-2
| The task shall run golanglint-ci and fail if there are any findings.

| REQ-TASK-BUILD-GO-3
a| The task shall run `go test`, creating code coverage and xUnit report.

* A shell script shall be executed prior to the tests if specified by the `pre-test-script` task parameter.
* All packages except vendored ones shall be tested.
* The artifacts shall be placed in the working directory (for SonarQube to pick them up) and in `.ods/artifacts`.
* If tests already ran for the commit being built, testing shall be skipped and the existing artifacts shall be copied into the working directory.

| REQ-TASK-BUILD-GO-4
a| The task shall build a Go module based Go binary into `docker/app`:

* The destination directory shall be customizable
* Paths in stack traces shall be trimmed
* The target operating system (`GOOS`) and architecture (`GOARCH`) shall be customizable
* CGO shall be disabled by default but shall be enablable by parameter.

| REQ-TASK-BUILD-GO-5
| See REQ-TASK-SHARED-1.

| REQ-TASK-BUILD-GO-6
| See REQ-TASK-SHARED-2.

|===

=== `ods-build-gradle`

[cols="1,3"]
|===
| REQ-TASK-BUILD-GRADLE-1
a| The task shall build a Gradle module that provides a gradle build script into `docker/app.jar`:

* The destination directory shall be customizable by exporting the environment variable `ODS_OUTPUT_DIR`.

| REQ-TASK-BUILD-GRADLE-2
a| The task shall run `gradlew clean build` to build the Java module:

* Options shall be passed to gradle

| REQ-TASK-BUILD-GRADLE-3
a| The task shall copy the generated unit test report into the folder `.ods/artifacts/xunit-reports`:

* The artifacts shall be placed in the working directory (for SonarQube to pick them up) and in .ods/artifacts.

| REQ-TASK-BUILD-GRADLE-4
a| The task shall copy the generated unit test coverage report into the folder `.ods/artifacts/code-coverage`:

* The artifacts shall be placed in the working directory (for SonarQube to pick them up) and in .ods/artifacts.

| REQ-TASK-BUILD-GRADLE-5
| See REQ-TASK-SHARED-1.

| REQ-TASK-BUILD-GRADLE-6
| See REQ-TASK-SHARED-2.

|===

=== `ods-build-python`

[cols="1,3"]
|===
| REQ-TASK-BUILD-PYTHON-1
| TODO

| REQ-TASK-BUILD-PYTHON-2
a| The task shall run `mypy` and `flake8` to lint source code and fail if there are any findings.

* The maximum allowed line length shall default to 120 and be defined by the `max-line-length` task parameter.

| REQ-TASK-BUILD-PYTHON-3
a| The task shall run `pytest`, creating code coverage and xUnit reports.

* A shell script shall be executed prior to the tests if specified by the `pre-test-script` task parameter.
* The artifacts shall be placed in the working directory (for SonarQube to pick them up) and in `.ods/artifacts`.

| REQ-TASK-BUILD-PYTHON-4
| See REQ-TASK-SHARED-1.

| REQ-TASK-BUILD-PYTHON-5
| See REQ-TASK-SHARED-2.

|===

=== `ods-build-typescript`

[cols="1,3"]
|===
| REQ-TASK-BUILD-TYPESCRIPT-1
| TODO

| REQ-TASK-BUILD-TYPESCRIPT-2
| See REQ-TASK-SHARED-1.

| REQ-TASK-BUILD-TYPESCRIPT-3
| See REQ-TASK-SHARED-2.

|===


=== `ods-package-image`

[cols="1,3"]
|===
| REQ-TASK-PACKAGE-IMAGE-1
| The task shall build a container image based on the `Dockerfile` in the Docker context directory.

* The Docker context directory shall default to `docker` and be parameterized by `docker-dir`.
* The Dockerfile shall default to `Dockerfile`, and be parameterized by `dockerfile`. The location shall be relative to the Docker context directory.
* The resulting image name and SHA shall be placed into `.ods/artifacts`.

| REQ-TASK-PACKAGE-IMAGE-2
| The task shall check if an image with the tag to built exist already in the target registry, and if so, skip the build.

| REQ-TASK-PACKAGE-IMAGE-3
| The task shall push the image to the target registry.

| REQ-TASK-PACKAGE-IMAGE-4
| If the Aqua scanner is installed in the base image, the  pushed image shall be scanned. The resulting report shall be placed in `.ods/artifacts` and attached as a code insight to Bitbucket.
|===

=== `ods-deploy-helm`

[cols="1,3"]
|===
| REQ-TASK-DEPLOY-HELM-1
a| The task shall skip when no `environment` is given.

| REQ-TASK-DEPLOY-HELM-2
a| The task shall push images into the target namespace.

* The images that are pushed are determined by the artifacts in `.ods/artifacts/image-digests`. Each artifact contains information from where to get the images.
* The target namespace is selected from the given `environment`.
* The target registry may also be external to the cluster in which the pipeline runs. The registry shall be identified by the `registryHost` field of the environment configuration, and the credential token of `apiCredentialsSecret` shall be used to authenticate.

| REQ-TASK-DEPLOY-HELM-3
a| The task shall upgrade (or install) a Helm chart.

* The Helm chart is expected at the location identified by the `chartDir` parameter (defaulting to `chart`).
* The task shall error if no chart can be found.
* A diff shall be performed before the upgrade/install. If there are no differences, upgrade/install shall be skipped.
* The upgrade/install shall wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful.
* Any values and secrets files corresponding to the environment and stage shall be respected (`values.yaml`, `secrets.yaml`, `values.<STAGE>.yaml`, `secrets.<STAGE>.yaml`, `values.<ENVIRONMENT>.yaml`, `secrets.<ENVIRONMENT>.yaml`; in that order of specificity).
* A values file containing the Git commit SHA shall be auto-generated and added to the Helm diff/upgrade invocation.
* Any encrypted secrets files shall be decrypted on the fly, using the private key provided by the `Secret` identified by the `private-key-secret` parameter (defaulting to `helm-secrets-private-key`). The secret shall expose the private key under the `sops.asc` field.
* The "app version" shall be set to the Git commit SHA and the "version" shall be set to given `version` if any, otherwise the chart version in `Chart.yaml`.
* Charts in any of the respositories configured in `ods.y(a)ml` shall be packaged according to the same rules and added as a subchart.
* The target namespace may also be external to the cluster in which the pipeline runs. The API server shall be identified by the `apiServer` field of the environment configuration, and the credential token of `apiCredentialsSecret` shall be used to authenticate.
|===

== Shared Task Requirements

Tasks above may refer to these shared requirements.

[cols="1,3"]
|===
| REQ-TASK-SHARED-1
a| The task shall run `sonar-scanner` on the sources, communicating with the SonarQube server specified by the `ods-sonar` config map and the `ods-sonar-auth` secret:

* The project name shall be fixed to `<PROJECT>-<COMPONENT>`
* If the server edition supports it, the branch parameter shall be set, unless the branch being built belongs to an open PR, in which case PR analysis parameter shall be sent instead.

| REQ-TASK-SHARED-2
a| The task shall be able to run in a subdirectory of the checked out repository.

* Generated artifacts shall be prefixed with `<SUBDIRECTORY>-`
* The SonarQube project shall be suffixed with `-<SUBDIRECTORY>`

|===
