# User Installation Guide
:toc:

This guide will show how to install `ods-pipeline` in an existing ODS project. It is possible to use the new Tekton pipelines approach and the classic Jenkins approach side by side.

Note that at the moment, `ods-pipeline` is somewhat compatible with an existing ODS 3.x/4.x installation, but it is not integrated (yet). If `ods-pipeline` gets integrated into OpenDevStack in the future, then the installation guide as presented below may not be needed anymore as the setup process might be automated then. However, the executed steps will likely be similar.

The guide will install the following required resources:

* `ConfigMap` and `Secret` resources, e.g. holding credentials of centrally installed tools such as Nexus and SonarQube
* Tekton Triggers related resources (e.g. `EventListener`, `TriggerTemplate`, etc.) including the ODS webhook interceptor, all of which allow to trigger pipelines in response to Bitbucket webhook requests

## Prerequisites

You'll need:

* A namespace in an OpenShift cluster (such as `foo-cd` from an existing ODS project) and a project in Bitbucket (such as `FOO`)
* `git`, `oc` and `helm` (with plugins link:https://github.com/databus23/helm-diff[`helm-diff`] and link:https://github.com/jkroepke/helm-secrets[`helm-secrets`]) installed locally
* to be logged into OpenShift on the command line

## Instructions

First, create a repository in Bitbucket, e.g. `foo-cd`. The name can be anything, but since the repository will define the resources in namespace `foo-cd` in code, it makes sense to mirror the namespace name. Clone the repository locally and make an initial commit, e.g. by adding a readme file.

Then, use `git subtree` to get the required sources. The following commands may look a bit complicated, but in a nutshell, they are simply adding one folder (`deploy/cd-namespace`) from the `opendestack/ods-pipeline` repository at the given revision (e.g. `master`) into your new local repository at the path `ods-pipeline`.

```
pipelineGitRef=v0.1.0 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --squash --prefix=deploy/cd-namespace -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree add --prefix=ods-pipeline subtree-split-branch-$pipelineGitRef
```

Once this is done, change to the new folder `ods-pipeline` to configure the values and secrets to use for the installation. It is recommended to encrypt the secrets at rest, therefore the following describes how to use the `helm-secrets` plugin to edit the secrets. For this, you'll need a link:https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key[GPG keypair], which fingerprint needs to be recorded in a `.sops.yaml`, e.g.:

```
creation_rules:
  - pgp: "A2F9 D4AF 800A 5499 3667 5C66 B92D F67B 0EF2 B057"
```

Now copy the default values files:

```
cp chart/values.yaml values.yaml
cat chart/secrets.yaml | helm secrets edit secrets.yaml
```


Now fill in the variables as described in the comments in both files. Then you can install the resources via `./install.sh -n foo-cd -f values.yaml,secrets.yaml` (make sure to replace the namespace). You may also use `--dry-run` to see the changes first.

Finally, run `oc -n foo-cd expose svc el-ods-pipeline` to expose the service listener. Make a note of the exposed URL as you'll need it to create webhooks in Bitbucket (together with the webhook secret that is stored in the `Secret/ods-bitbucket-webhook` resource).

Now your cd namespace is fully setup and you can start to utilize Tekton pipelines for your repositories. Please note that the `pipeline` serviceaccount in your `foo-cd` namespace needs at `edit` or even `admin` permissions in the Kubernetes namespaces it deploys to (e.g. `foo-dev` and `foo-test`).

See the link:ods-configuration.adoc[ODS.YAML reference] for more information on usage.

## Updating

You may fetch updates (e.g. new versions) of `ods-pipeline` like this:
```
pipelineGitRef=v0.1.0 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --squash --prefix=deploy/cd-namespace -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree merge --prefix=ods-pipeline subtree-split-branch-$pipelineGitRef --squash
```

Now, compare if any new values have been introduced and update the values and secrets file accordingly.

Afterwards you can update the resources via `./install.sh -n foo-cd -f values.yaml,secrets.yaml`. You may also use `--dry-run` to see the changes first.
