# User Installation Guide
:toc:

This guide will show how to install `ods-pipeline` in an existing ODS project. It is possible to use the new Tekton pipelines approach and the classic Jenkins approach side by side.

Note that at the moment, `ods-pipeline` is somewhat compatible with an existing ODS 3.x/4.x installation, but it is not integrated (yet). If `ods-pipeline` gets integrated into OpenDevStack in the future, then the installation guide as presented below may not be needed anymore as the setup process might be automated then. However, the executed steps will likely be similar.

The guide will install the following required resources:

* `ConfigMap` and `Secret` resources, e.g. holding credentials of centrally installed tools such as Nexus and SonarQube
* Tekton Triggers related resources (e.g. `EventListener`, `TriggerTemplate`, etc.) including the ODS webhook interceptor, all of which allow to trigger pipelines in response to Bitbucket webhook requests

## Prerequisites

You'll need:

* A namespace in an OpenShift cluster (such as `foo-cd` from an existing ODS project) and a project in Bitbucket (such as `FOO`)
* `git`, `oc` and `helm` (with plugins link:https://github.com/databus23/helm-diff[`helm-diff`] and link:https://github.com/jkroepke/helm-secrets[`helm-secrets`]) installed locally
* to be logged into OpenShift on the command line

## Instructions

First, create a repository in Bitbucket, e.g. `foo-cd`. The name can be anything, but since the repository will define the resources in namespace `foo-cd` in code, it makes sense to mirror the namespace name. Clone the repository locally and make an initial commit, e.g. by adding a readme file.

Then, use `git subtree` to get the required sources. The following commands may look a bit complicated, but in a nutshell, they are simply adding one folder (`deploy/cd-namespace`) from the `opendestack/ods-pipeline` repository at the given revision (e.g. `master`) into your new local repository at the path `ods-pipeline`.

```
pipelineGitRef=v0.1.1 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --prefix=deploy/cd-namespace -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree add --squash --prefix=ods-pipeline subtree-split-branch-$pipelineGitRef
```

Once this is done, change to the new folder `ods-pipeline` to configure the values and secrets to use for the installation.

For the values, just run:
```
cp chart/values.yaml values.yaml
```

Regarding the secrets, it is recommended to encrypt them at rest, therefore the following describes how to first encrypt them, but also how to edit them using the `helm-secrets` plugin.

For this, you'll need to install `link:https://github.com/mozilla/sops[sops]` and `link:https://github.com/FiloSottile/age[age]` for en-/decryption of the `secrets.yaml` file.

As described in the `sops` link:https://github.com/mozilla/sops#22encrypting-using-age[documentation], when decrypting
using `age`, `sops` will look for a text file name `keys.txt` located in a `sops subdirectory` of your user
configuration directory. On Linux, this would be `$XDG_CONFIG_HOME/sops/age/keys.txt` (if `$XDG_CONFIG_HOME` is not set,
it is usually `$HOME/.config`). On macOS, this would be`$HOME/Library/Application Support/sops/age/keys.txt`. On Windows,
this would be `%AppData%\sops\age\keys.txt`. You can specify the location of this file manually by setting the
environment variable `SOPS_AGE_KEY_FILE`. We will refer to this user configuration directory as `<your_user_config_dir>`.

Knowing this, we create a key pair for encryption by running:

```
mkdir -p <your_user_config_dir>/sops/age
age-keygen -o <your_user_config_dir>/sops/age/keys.txt
```

This prints as a result the public key (alternatively you can find it in the `keys.txt`) which looks similar to this:
```
Public key: age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
```

Take the public key and use it to create an encrypted version of your `secrets.yaml`:

```
sops --encrypt --age age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p chart/secrets.yaml > secrets.yaml
```

You can edit the secrets with:
```
helm secrets edit secrets.yaml
```


Now fill in the variables as described in the comments in both (values.yaml and secrets.yaml) files. Then you can install the resources via `./install.sh -n foo-cd -f values.yaml,secrets.yaml` (make sure to replace the namespace). You may also use `--dry-run` to see the changes first.

Finally, run `oc -n foo-cd expose svc el-ods-pipeline` to expose the service listener. Make a note of the exposed URL as you'll need it to create webhooks in Bitbucket (together with the webhook secret that is stored in the `Secret/ods-bitbucket-webhook` resource).

Now your cd namespace is fully setup and you can start to utilize Tekton pipelines for your repositories. Please note that the `pipeline` serviceaccount in your `foo-cd` namespace needs at `edit` or even `admin` permissions in the Kubernetes namespaces it deploys to (e.g. `foo-dev` and `foo-test`).

See the link:getting-started.adoc[Getting Started] guide for more information on usage.

## Updating

You may fetch updates (e.g. new versions) of `ods-pipeline` like this:
```
pipelineGitRef=v0.1.1 # Pick the version you want to install

git fetch --depth=1 https://github.com/opendevstack/ods-pipeline.git $pipelineGitRef:ods-pipeline-$pipelineGitRef && \
git checkout ods-pipeline-$pipelineGitRef && \
git subtree split --squash --prefix=deploy/cd-namespace -b subtree-split-branch-$pipelineGitRef && \
git checkout - && \
git subtree merge --prefix=ods-pipeline subtree-split-branch-$pipelineGitRef --squash
```

Now, compare if any new values have been introduced and update the values and secrets file accordingly.

Afterwards you can update the resources via `./install.sh -n foo-cd -f values.yaml,secrets.yaml`. You may also use `--dry-run` to see the changes first.

Once the resources in your namespace are updated, you can update the `ods.yaml` files in your repository and point to the new tasks, e.g. changing `ods-build-go-v0-1-0` to `ods-build-go-v0-1-1`.
