apiVersion: v1
kind: Template
metadata:
  name: ods-build-python
parameters:
  - name: GIT_URL
    description: "Git repository URL"
  - name: SOURCE_SERCET
    description: "Name of source secret to access GIT_URL"
    value: cd-user-token
objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ods-build-python
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: "ods-build-python:latest"
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: build/package/Dockerfile.python
          from:
            kind: DockerImage
            name: "registry.redhat.io/ubi8"
          pullSecret:
            name: registry.redhat.io
      postCommit: {}
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: master
        sourceSecret:
          name: ${SOURCE_SERCET}
      runPolicy: Serial
