name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          args: --timeout=5m0s
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: test/testdata/workspaces
