name: Tekton Tasks Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_BASE: ${{ github.repository }}

jobs:
  pipeline-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      -
        name: Check if docs are up-to-date
        run: ./.github/workflows/check-docs.sh
      -
        name: Run tests
        run: |
          make test
      -
        name: Log into ghcr.io
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push images to ghcr.io
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMAGES: finish pipeline-manager start
        run: |
          images=(${{ env.IMAGES }})
          for image in ${images[*]}
          do
            echo "::group::Push $image to ghcr.io"
            docker tag localhost:5000/ods-pipeline/$image:latest ghcr.io/${{ env.IMAGE_BASE }}/$image:latest
            docker push ghcr.io/${{ env.IMAGE_BASE }}/$image:latest
            echo "::endgroup::"
          done
      -
        name: Configure Git
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      -
        name: Run chart-releaser
        if: ${{ github.event_name != 'pull_request' }}
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: deploy
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
