name: Tekton Tasks Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-images:
    name: Build ODS images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["buildah", "finish", "go-toolset", "gradle-toolset", "helm", "sonar", "start", "pipeline-manager", "python-toolset", "node16-typescript-toolset"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: build/package/Dockerfile.${{ matrix.image }}
          tags: localhost:5000/ods/ods-${{ matrix.image }}:latest
          outputs: type=docker,dest=/tmp/image-ods-${{ matrix.image }}.tar
      - 
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildx-image-ods-${{ matrix.image }}
          path: /tmp/image-ods-${{ matrix.image }}.tar
          retention-days: 1

  pipeline-tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - 
        name: Download image artifacts
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup KinD cluster with internal registry
        working-directory: scripts
        run: ./kind-with-registry.sh
      -
        name: Push buildah image
        run: |
          docker load --input /tmp/buildx-image-ods-buildah/image-ods-buildah.tar
          docker push localhost:5000/ods/ods-buildah:latest
          docker rmi localhost:5000/ods/ods-buildah:latest
      -
        name: Push finish image
        run: |
          docker load --input /tmp/buildx-image-ods-finish/image-ods-finish.tar
          docker push localhost:5000/ods/ods-finish:latest
          docker rmi localhost:5000/ods/ods-finish:latest
      -
        name: Push go-toolset image
        run: |
          docker load --input /tmp/buildx-image-ods-go-toolset/image-ods-go-toolset.tar
          docker push localhost:5000/ods/ods-go-toolset:latest
          docker rmi localhost:5000/ods/ods-go-toolset:latest
      -
        name: Push gradle-toolset image
        run: |
          docker load --input /tmp/buildx-image-ods-gradle-toolset/image-ods-gradle-toolset.tar
          docker push localhost:5000/ods/ods-gradle-toolset:latest
          docker rmi localhost:5000/ods/ods-gradle-toolset:latest
      -
        name: Push helm image
        run: |
          docker load --input /tmp/buildx-image-ods-helm/image-ods-helm.tar
          docker push localhost:5000/ods/ods-helm:latest
          docker rmi localhost:5000/ods/ods-helm:latest
      -
        name: Push sonar image
        run: |
          docker load --input /tmp/buildx-image-ods-sonar/image-ods-sonar.tar
          docker push localhost:5000/ods/ods-sonar:latest
          docker rmi localhost:5000/ods/ods-sonar:latest
      -
        name: Push start image
        run: |
          docker load --input /tmp/buildx-image-ods-start/image-ods-start.tar
          docker push localhost:5000/ods/ods-start:latest
          docker rmi localhost:5000/ods/ods-start:latest
      -
        name: Push pipeline-manager image
        run: |
          docker load --input /tmp/buildx-image-ods-pipeline-manager/image-ods-pipeline-manager.tar
          docker push localhost:5000/ods/ods-pipeline-manager:latest
          docker rmi localhost:5000/ods/ods-pipeline-manager:latest
      -
        name: Push python-toolset image
        run: |
          docker load --input /tmp/buildx-image-ods-python-toolset/image-ods-python-toolset.tar
          docker push localhost:5000/ods/ods-python-toolset:latest
          docker rmi localhost:5000/ods/ods-python-toolset:latest
      -
        name: Push node16-typescript-toolset image
        run: |
          docker load --input /tmp/buildx-image-ods-node16-typescript-toolset/image-ods-node16-typescript-toolset.tar
          docker push localhost:5000/ods/ods-node16-typescript-toolset:latest
          docker rmi localhost:5000/ods/ods-node16-typescript-toolset:latest
      -
        name: Delete image tarballs
        run: |
          rm -rf /tmp/buildx-image-*
      -
        name: Setup kubectl
        uses: azure/setup-kubectl@v1
        id: install
      -
        name: Install Tekton Core Components
        run: make install-tekton-pipelines
      - 
        name: Show disk space
        run: df -h
      -
        name: Spin up Bitbucket container
        run: make run-bitbucket
      -
        name: Spin up Nexus container
        run: make run-nexus
      -
        name: Spin up SonarQube container
        run: make run-sonarqube
      - 
        name: Show disk space
        run: df -h
      -
        name: Install cluster tasks
        run: make install-ods-tasks-kind
      -
        name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Check if sidecar tasks are up-to-date
        run: ./.github/workflows/check-sidecar-tasks.sh
      -
        name: Check if docs are up-to-date
        run: ./.github/workflows/check-docs.sh
      -
        name: Run tests
        run: |
          set -o pipefail
          go test -v ./cmd/... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
          go test -v ./internal/... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
          go test -v ./pkg/... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
          go test -timeout 30m -v ./test/tasks/... -always-keep-tmp-workspaces | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
          go test -timeout 10m -v ./test/e2e/... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
