name: Tekton Tasks Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  # github.repository as <account>/<repo>
  IMAGE_BASE: ${{ github.repository }}

jobs:
  pipeline-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      -
        name: Check if docs are up-to-date
        run: ./.github/workflows/check-docs.sh
      -
        name: Run tests
        run: |
          make test
      # -
      #   name: Log into ghcr.io
      #   if: ${{ github.event_name != 'pull_request' }}
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Push images to ghcr.io
      #   if: ${{ github.event_name != 'pull_request' }}
      #   run: |
      #     images=(${{ env.IMAGES }})
      #     for image in ${images[*]}
      #     do
      #       echo "::group::Push ods-$image to ghcr.io"
      #       docker tag localhost:5000/ods/ods-$image:latest ghcr.io/${{ env.IMAGE_BASE }}/ods-$image:latest
      #       docker push ghcr.io/${{ env.IMAGE_BASE }}/ods-$image:latest
      #       echo "::endgroup::"
      #     done
