global:
  imageTag: latest
  taskSuffix: '-v0-4-0'

##
# setup chart
##
setup:
  enabled: true
  # General
  serviceAccountName: 'pipeline'

  # Cluster
  consoleUrl: 'http://example.com'

  # Pipeline Manager
  pipelineManager:
    storageProvisioner: ''
    storageClassName: 'standard'
    storageSize: '6Gi'
    replicaCount: 1
    image:
      registry: localhost:5000
      namespace: ods
      repository: ods-pipeline-manager
      pullPolicy: Always
      tag: "latest"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  # Notification Webhook
  notification:
    # notifications are disabled by default, i.e. the ConfigMap won't be installed
    enabled: false

##
# tasks chart
##
tasks:
  # enabled: true
  # To test with the latest public ods-pipeline images, set global.imageTag to 'latest' and use:
  # registry: ghcr.io
  # namespace: opendevstack/ods-pipeline

  registry: localhost:5000
  namespace: ods
  pushRegistry: kind-registry.kind:5000

##
# images chart
##
images:
  enabled: false
