global:
  imageTag: latest
  taskSuffix: ''

setup:
  # Cluster
  consoleUrl: 'http://example.com'
  # Pipeline Manager
  pipelineManager:
    storageProvisioner: ''
    storageClassName: 'standard'
    storageSize: '2Gi'
    image:
      registry: localhost:5000
      namespace: ods
      tag: "latest"

tasks:
  # To test with the latest public ods-pipeline images, set global.imageTag to 'latest' and use:
  # registry: ghcr.io
  # namespace: opendevstack/ods-pipeline
  registry: localhost:5000
  namespace: ods
  pushRegistry: kind-registry.kind:5000

images:
  enabled: false
